/*
 * Unit tests for the `gramark --check` bridge. Run with: `npm test`
 * (i.e. `node --test gramark-check.test.ts`).
 *
 * These exercise the structure and drift gates, the hashing model, and the
 * diagram-mode conversion directly, with small in-memory fixtures, plus one
 * `fmt` round-trip on a temp directory. The lint gate shells out to
 * markdownlint-cli2 and is covered end-to-end by `grammar/` in CI rather
 * than here.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  parse,
  checkStructure,
  checkDrift,
  convertDiagrams,
  fmt,
  grammarHashes,
  longestBacktickRun,
  lockPathFor,
  regenerateTables,
} from "./gramark-check.ts";
import { parseProduction } from "./railroad.ts";

// A canonical, contract-clean grammar document, built line-by-line so the
// nested ```gramark fences can use backticks freely (double-quoted strings, unlike
// template literals, treat the backtick as an ordinary character).
function miniDoc(
  opts: {
    precedence?: boolean;
    tokens?: boolean;
    settings?: boolean;
    rule?: string;
  } = {},
): string {
  const rule = opts.rule ?? "  : 'x'   {% \\_ -> 1 %}";
  const lines = [
    "# Mini",
    "",
    "A one-rule grammar used as a test fixture.",
    "",
  ];
  if (opts.settings) {
    lines.push(
      "## General settings",
      "",
      "```gramark settings",
      "%lang javascript",
      "```",
      "",
    );
  }
  if (opts.tokens) {
    lines.push("## Tokens", "", "```gramark tokens", "X : /x/", "```", "");
  }
  lines.push("## A", "", "```gramark", "A", rule, "```", "");
  if (opts.precedence) {
    lines.push(
      "## Precedence",
      "",
      "```gramark precedence",
      "%left 'x'",
      "```",
      "",
    );
  }
  lines.push(
    "## Error messages",
    "",
    "```gramark errors",
    "state 0:",
    "  Expected an `x` here.",
    "```",
    "",
    "## Generated tables",
    "",
    "Generated by Gramark — do not edit.",
    "",
    "| Nonterminal | FIRST | FOLLOW |",
    "| ----------- | ----- | ------ |",
    "| `A`         | `x`   | `$`    |",
  );
  return lines.join("\n") + "\n";
}

test("parse extracts headings, blocks, and the lr nonterminal", () => {
  const doc = parse(miniDoc());
  assert.equal(doc.headings[0]?.level, 1);
  assert.equal(doc.headings[0]?.text, "Mini");

  const lrBlock = doc.blocks.find((b) => b.info === "gramark");
  assert.ok(lrBlock, "expected an lr block");
  assert.equal(lrBlock.nonterminal, "A");
  assert.equal(lrBlock.fenceLen, 3);

  // The precedence/errors fences are parsed but are not lr-nonterminal rules.
  assert.equal(
    doc.blocks.filter((b) => b.info === "gramark" && b.nonterminal).length,
    1,
  );
});

test("longestBacktickRun counts the longest run", () => {
  assert.equal(longestBacktickRun("a `x` b ``y`` c"), 2);
  assert.equal(longestBacktickRun("no backticks here"), 0);
  assert.equal(longestBacktickRun("```triple```"), 3);
});

test("lockPathFor swaps the .grmk.md extension for .grmk.lock", () => {
  assert.equal(lockPathFor("grammar/lr.grmk.md"), "grammar/lr.grmk.lock");
  assert.equal(lockPathFor("a/b/calc.grmk.md"), "a/b/calc.grmk.lock");
});

test("checkStructure accepts a canonical document", () => {
  assert.deepEqual(checkStructure(parse(miniDoc())), []);
});

test("checkStructure accepts an optional Precedence section", () => {
  assert.deepEqual(checkStructure(parse(miniDoc({ precedence: true }))), []);
});

test("checkStructure accepts a Tokens section before the nonterminals (lexer-spec §9)", () => {
  assert.deepEqual(checkStructure(parse(miniDoc({ tokens: true }))), []);
});

test("checkStructure accepts a General settings section first (%lang)", () => {
  assert.deepEqual(
    checkStructure(parse(miniDoc({ settings: true, tokens: true }))),
    [],
  );
});

test("checkStructure rejects a Tokens section out of place (after the nonterminal)", () => {
  // `## Tokens` must precede the first nonterminal; here it follows `## A`.
  const misplaced = miniDoc().replace(
    "## Error messages",
    "## Tokens\n\n```gramark tokens\nX : /x/\n```\n\n## Error messages",
  );
  const fails = checkStructure(parse(misplaced));
  assert.ok(
    fails.some((f) => /out of canonical order/.test(f)),
    `expected an ordering failure, got: ${JSON.stringify(fails)}`,
  );
});

test("grammarHashes covers the lr tokens block (a token change is drift-visible)", () => {
  const withTokens = grammarHashes(
    parse(miniDoc({ tokens: true })),
  ).grammarSha256;
  const without = grammarHashes(parse(miniDoc())).grammarSha256;
  assert.notEqual(withTokens, without);
});

test("checkStructure ignores ###+ presentational grouping headings (D29)", () => {
  // A heading deeper than H2 carries no structural meaning: it is free grouping
  // ("Expressions", "Statements") or a subsection. The gate must pass it through
  // — the strict layer is the H2-or-reserved-section one — while the GitHub TOC
  // still nests it. Here a `### Notes` subsection sits inside the `## A` section.
  const grouped = miniDoc().replace(
    "## A\n\n",
    "## A\n\n### Notes\n\nA presentational subsection the structure gate ignores.\n\n",
  );
  assert.deepEqual(checkStructure(parse(grouped)), []);
});

test("checkStructure flags a fence that is too wide", () => {
  // A 4-backtick fence around content with no backtick runs is wrong.
  const broken = miniDoc()
    .replace("```gramark\nA", "````gramark\nA")
    .replace("\n```\n\n## Error", "\n````\n\n## Error");
  const fails = checkStructure(parse(broken));
  assert.ok(
    fails.some((f) => /backticks; contract requires 3/.test(f)),
    `expected a fence-width failure, got: ${JSON.stringify(fails)}`,
  );
});

test("checkStructure flags H2 sections out of canonical order", () => {
  const reordered = miniDoc().replace("## Error messages", "## Surprise");
  const fails = checkStructure(parse(reordered));
  assert.ok(
    fails.some((f) => /out of canonical order/.test(f)),
    `expected an ordering failure, got: ${JSON.stringify(fails)}`,
  );
});

test("grammarHashes is deterministic and keyed by nonterminal", () => {
  const a = grammarHashes(parse(miniDoc()));
  const b = grammarHashes(parse(miniDoc()));
  assert.equal(a.grammarSha256, b.grammarSha256);
  assert.ok(a.ruleHashes["A"], "expected a hash for rule A");

  const changed = grammarHashes(
    parse(miniDoc({ rule: "  : 'y'   {% \\_ -> 2 %}" })),
  );
  assert.notEqual(changed.grammarSha256, a.grammarSha256);
  assert.notEqual(changed.ruleHashes["A"], a.ruleHashes["A"]);
});

test("fmt then checkDrift: clean for the formatted grammar, stale after an edit", () => {
  const dir = mkdtempSync(join(tmpdir(), "gramark-test-"));
  try {
    const file = join(dir, "mini.grmk.md");
    const src = miniDoc();
    writeFileSync(file, src);

    fmt(file, parse(src), "sidecar");
    assert.deepEqual(
      checkDrift(file, parse(src)),
      [],
      "freshly locked file should not drift",
    );

    const edited = parse(miniDoc({ rule: "  : 'y'   {% \\_ -> 2 %}" }));
    const fails = checkDrift(file, edited);
    assert.ok(
      fails.some((f) => /stale/.test(f)),
      `expected a drift failure after editing the grammar, got: ${JSON.stringify(fails)}`,
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// A one-rule document with a sidecar image-link diagram.
const sidecarDoc = [
  "# Mini",
  "",
  "## A",
  "",
  "```gramark",
  "A",
  "  : 'x' B",
  "```",
  "",
  "![Railroad diagram for the A rule](diagrams/a.svg)",
  "",
  "## Error messages",
  "",
].join("\n");

const nts = new Set(["A"]);
const content = new Map([["A", "A\n  : 'x' B"]]);

test("convertDiagrams: sidecar -> mermaid embeds a tagged fence, removing the image", () => {
  const mm = convertDiagrams(sidecarDoc, content, nts, "mermaid");
  assert.match(
    mm,
    /```mermaid\n%% Railroad diagram for the A rule\nflowchart LR/,
  );
  assert.doesNotMatch(mm, /\]\(diagrams\/a\.svg\)/);
});

test("convertDiagrams round-trips and each direction is idempotent", () => {
  const mm = convertDiagrams(sidecarDoc, content, nts, "mermaid");
  // mermaid -> sidecar recovers the original document
  assert.equal(convertDiagrams(mm, content, nts, "sidecar"), sidecarDoc);
  // each direction is a fixed point
  assert.equal(
    convertDiagrams(sidecarDoc, content, nts, "sidecar"),
    sidecarDoc,
  );
  assert.equal(convertDiagrams(mm, content, nts, "mermaid"), mm);
});

test("regenerateTables rewrites the FIRST/FOLLOW table from the grammar", () => {
  const doc = [
    "# G",
    "",
    "## S",
    "",
    "```gramark",
    "S",
    "  : 'a' S",
    "  | 'a'",
    "```",
    "",
    "## Generated tables",
    "",
    "Generated by Gramark — do not edit.",
    "",
    "| Nonterminal | FIRST | FOLLOW |",
    "| ----------- | ----- | ------ |",
    "| `S`         | WRONG | WRONG  |",
    "",
    "No conflicts.",
    "",
  ].join("\n");
  const prods = [parseProduction("S\n  : 'a' S\n  | 'a'", new Set(["S"]))];
  const out = regenerateTables(doc, prods);
  // FIRST(S) = { a }; FOLLOW(S) = { $ } (the start symbol, nothing follows S).
  assert.match(out, /\| `S` +\| `a` +\| `\$` +\|/);
  assert.doesNotMatch(out, /WRONG/);
  // The caption and the conflict-summary line are preserved.
  assert.match(out, /Generated by Gramark — do not edit\./);
  assert.match(out, /No conflicts\./);
  // Idempotent.
  assert.equal(regenerateTables(out, prods), out);
});
