-- | Source-emitting codegen: generate the `lr` reduce function from the IR.
-- |
-- | This is the keystone the plan calls [S2]. `Grammark.Lr.reduce` is written
-- | by hand today; here we *emit* an equivalent from `grammark-ir` plus the
-- | `lr` typed-AST profile (the per-symbol `SemVal` constructor map). The
-- | generated module is committed at `src/Grammark/Generated/LrReduce.purs`
-- | and proven by the self-host oracle in `Test.Codegen`: the parser driven by
-- | the generated reduce reads `grammar/lr.gram.md` back to `bootstrapGrammar`.
-- |
-- | The profile is the legitimate extra input a typed-AST backend needs: the
-- | grammar alone says nothing about which `SemVal` carries which symbol. Given
-- | it, codegen is a pure function of the IR — each production becomes a case
-- | branch that unwraps its kids by their symbols' constructors, splices the
-- | action body verbatim, and wraps the result by the left-hand side's.
-- |
-- | Regenerate after a deliberate change with:
-- |   spago run --main Grammark.Codegen.Main
module Grammark.Codegen
  ( lrConMap
  , lrReduceModulePath
  , generateLrReduce
  ) where

import Prelude

import Data.Array (zipWith)
import Data.Array as Array
import Data.Map (Map)
import Data.Map as Map
import Data.Maybe (Maybe(..), fromMaybe)
import Data.String (Pattern(..))
import Data.String as String
import Data.Tuple (Tuple(..), snd)
import Grammark.IR (IR, IRRef(..), IRRule, IRTerminal(..))

-- | Where the generated module is written and read back from.
lrReduceModulePath :: String
lrReduceModulePath = "src/Grammark/Generated/LrReduce.purs"

-- | The `lr` typed-AST profile: each grammar symbol mapped to the `SemVal`
-- | constructor that carries its value. Punctuation/`NL` never carry a named
-- | parameter, so their entries are present only for completeness.
lrConMap :: Map String String
lrConMap = Map.fromFoldable
  [ Tuple "Grammar" "VGrammar"
  , Tuple "RuleList" "VRules"
  , Tuple "Rule" "VRule"
  , Tuple "Body" "VAlts"
  , Tuple "AltTail" "VAlts"
  , Tuple "Alt" "VAlt"
  , Tuple "SymList" "VSyms"
  , Tuple "Sym" "VSym"
  , Tuple "Args" "VSyms"
  , Tuple "Action" "VMaybeStr"
  , Tuple "Label" "VMaybeStr"
  , Tuple "IDENT" "VStr"
  , Tuple "TERM_LIT" "VStr"
  , Tuple "ACTION" "VStr"
  , Tuple "LABEL" "VStr"
  , Tuple "ATTR" "VStr"
  ]

-- | Emit the full `Grammark.Generated.LrReduce` module text.
generateLrReduce :: IR -> String
generateLrReduce ir =
  header arrayImport
    <> body
    <> "\n"
    <> fallback
    <> "\n"
  where
  names = symbolNames ir
  body = String.joinWith "\n" (map (genBranch lrConMap names) ir.grammar.rules)
  -- Import only the Data.Array helpers the emitted reduce actually uses, so the
  -- generated module stays clean under `--strict` (no unused-import warning).
  used name = String.contains (Pattern name) body
  arrayImport = case used "cons", used "snoc" of
    true, true -> [ "import Data.Array (cons, snoc)" ]
    true, false -> [ "import Data.Array (cons)" ]
    false, true -> [ "import Data.Array (snoc)" ]
    false, false -> []

header :: Array String -> String
header arrayImport =
  String.joinWith "\n"
    ( [ "-- | GENERATED by Grammark codegen from the `lr` grammar. Do not edit."
      , "-- |"
      , "-- | This is the reduce `Grammark.Lr` writes by hand, emitted from the IR"
      , "-- | and the `lr` typed-AST profile. The self-host oracle (`Test.Codegen`)"
      , "-- | proves it: the parser driven by this reduce reconstructs"
      , "-- | `bootstrapGrammar`. Regenerate with `spago run --main"
      , "-- | Grammark.Codegen.Main`."
      , "module Grammark.Generated.LrReduce (reduce) where"
      , ""
      , "import Prelude"
      , ""
      ]
        <> arrayImport
        <>
          [ "import Data.Maybe (Maybe(Just, Nothing))"
          , "import Grammark.Lr (SemVal(VGrammar, VRules, VRule, VAlts, VAlt, VSyms, VSym, VMaybeStr, VStr, VErr))"
          , "import Grammark.Syntax (Alt(Alt), Grammar(Grammar), Rule(Rule), Sym(Ref, Lit, Rep, Star, Opt, Macro, Field))"
          , ""
          , "reduce :: Int -> Array SemVal -> SemVal"
          , "reduce p kids = case p, kids of"
          , ""
          ]
    )

fallback :: String
fallback = "  _, _ -> VErr (\"unexpected reduce shape for production \" <> show p)"

-- Name lookups: a ref resolved to its symbol name, and a rule's LHS name.
type Names = { ref :: IRRef -> String, lhs :: Int -> String }

symbolNames :: IR -> Names
symbolNames ir =
  { ref: \r -> case r of
      IRRefNT i _ -> look ntById i
      IRRefT i _ -> look termById i
  , lhs: \i -> look ntById i
  }
  where
  ntById = Map.fromFoldable (map (\n -> Tuple n.id n.name) ir.grammar.nonterminals)
  termById = Map.fromFoldable (map (\t -> Tuple (termId t) (termName t)) ir.grammar.terminals)
  look m i = fromMaybe "?" (Map.lookup i m)

termId :: IRTerminal -> Int
termId = case _ of
  IRLiteral i _ -> i
  IRClass i _ -> i

termName :: IRTerminal -> String
termName = case _ of
  IRLiteral _ s -> s
  IRClass _ n -> n

-- One case branch for a production: `  <p>, [ <pats> ] -> <wrap> (<body>)`.
genBranch :: Map String String -> Names -> IRRule -> String
genBranch conMap names rule =
  case parseLambda (actionOf rule) of
    Nothing -> "  " <> show rule.id <> ", _ -> VErr \"no action for production " <> show rule.id <> "\""
    Just { params, body } ->
      let
        symNames = map names.ref rule.rhs
        pats = zipWith (mkPat conMap) symNames params
        wrap = fromMaybe "VErr" (Map.lookup (names.lhs rule.lhs) conMap)
      in
        "  " <> show rule.id <> ", [ " <> String.joinWith ", " pats <> " ] -> "
          <> wrap
          <> " ("
          <> body
          <> ")"

-- A kid pattern: `_` for an ignored parameter, else `<Con> <name>`.
mkPat :: Map String String -> String -> String -> String
mkPat conMap symName param =
  if param == "_" then "_"
  else fromMaybe ("?" <> symName) (Map.lookup symName conMap) <> " " <> param

actionOf :: IRRule -> String
actionOf rule = fromMaybe "" (map snd (Array.find (\(Tuple k _) -> k == "purescript") rule.actions))

-- Split `\p1 p2 -> body` into its parameters and body text.
parseLambda :: String -> Maybe { params :: Array String, body :: String }
parseLambda s = case String.stripPrefix (Pattern "\\") (String.trim s) of
  Nothing -> Nothing
  Just rest -> case String.indexOf (Pattern "->") rest of
    Nothing -> Nothing
    Just i ->
      Just
        { params: Array.filter (_ /= "") (String.split (Pattern " ") (String.trim (String.take i rest)))
        , body: String.trim (String.drop (i + 2) rest)
        }
