package gramaire

// A `recognizer` + `cst` codegen backend: `gramaire-ir` in, a TypeScript
// parser out. Emits a self-contained ES module: the LR(1) shift/reduce
// driver over ACTION/GOTO/PRODS tables building the generic CST, plus
// the typed Visitor (D24) and its fold catamorphism.
// Ported from src/Gramaire/Backend/Ts.purs.
object BackendTs:
  val backend: Backend = Backend(
    name = "ts",
    capabilities = Vector(Capability.Recognizer, Capability.Cst),
    strategies = Backend.lrOnly,
    emit = ir =>
      Vector(
        Output(s"${ir.grammar.name}.ts", emit(ir)),
        Output(s"${ir.grammar.name}.d.ts", emitDts(ir))
      )
  )

  private def banner(ir: IR, what: String): String =
    s"// GENERATED by Gramaire from the `${ir.grammar.name}` grammar — $what.\n" +
      "// Do not edit; regenerate with `gramaire emit --backend ts`."

  // The CST node vocabulary, shared by the `.ts` and `.d.ts`.
  private val cstTypes: String =
    Vector(
      "export type Token = { terminal: string; text: string };",
      "export type CstToken = { token: string; text: string };",
      "export type CstBranch = { rule: number; children: CstNode[] };",
      "export type CstNode = CstBranch | CstToken;"
    ).mkString("\n")

  private def terminalId(t: IRTerminal): Int = t match
    case IRTerminal.IRLiteral(i, _) => i
    case IRTerminal.IRClass(i, _)   => i

  // A terminal's lexer name: a literal's spelling, a class's name.
  private def terminalNames(ir: IR): Map[Int, String] =
    ir.grammar.terminals.map {
      case IRTerminal.IRLiteral(i, spelling) => i -> spelling
      case IRTerminal.IRClass(i, name)       => i -> name
    }.toMap

  private def onName(names: Map[Int, String], o: IROn): String = o match
    case IROn.OnTerm(i) => names.getOrElse(i, s"t?$i")
    case IROn.OnEof     => ""

  // A TS/JSON object key as a quoted string literal (canonical escaping).
  private def key(s: String): String = Json.stringify(Json.JString(s))

  // ACTION[state][terminalName] -> action; the empty-string key is end-of-input.
  private def actionConst(ir: IR): String =
    val names = terminalNames(ir)
    def act(a: IRAct): String = a match
      case IRAct.ActShift(n)  => s"{ shift: $n }"
      case IRAct.ActReduce(n) => s"{ reduce: $n }"
      case IRAct.ActAccept    => "{ accept: true }"
    def entry(e: IRActionEntry): String = s"${key(onName(names, e.on))}: ${act(e.action)}"
    def row(r: IRActionRow): String = s"  ${r.state}: { ${r.entries.map(entry).mkString(", ")} },"
    "const ACTION: Record<number, Record<string, Act>> = {\n" + ir.tables.action
      .map(row)
      .mkString("\n") + "\n};\n"

  // GOTO[state][nonterminalId] -> state.
  private def gotoConst(ir: IR): String =
    def row(r: IRGotoRow): String =
      s"  ${r.state}: { ${r.entries.map(e => s"${e.nonterminal}: ${e.to}").mkString(", ")} },"
    "\nconst GOTO: Record<number, Record<number, number>> = {\n" + ir.tables.goto
      .map(row)
      .mkString("\n") + "\n};\n"

  // PRODS[ruleId] -> { lhs nonterminal id, rhs length }, in rule-id order.
  private def prodsConst(ir: IR): String =
    def prod(r: IRRule): String = s"  { lhs: ${r.lhs}, len: ${r.rhs.length} }, // ${r.id}"
    "\nconst PRODS: { lhs: number; len: number }[] = [\n" + ir.grammar.rules
      .sortBy(_.id)
      .map(prod)
      .mkString("\n") + "\n];"

  private val parseFn: String =
    Vector(
      "type Act = { shift: number } | { reduce: number } | { accept: true };",
      "",
      "// The generic LR(1) shift/reduce driver, building the CST.",
      "export function parse(tokens: Token[]): CstNode {",
      "  const states: number[] = [0];",
      "  const values: CstNode[] = [];",
      "  let pos = 0;",
      "  for (;;) {",
      "    const state = states[states.length - 1]!;",
      "    const tok = tokens[pos];",
      "    const look = tok ? tok.terminal : \"\"; // \"\" is end-of-input",
      "    const act = ACTION[state]?.[look];",
      "    if (!act) {",
      "      throw new ParseError(",
      "        tok",
      "          ? `unexpected token ${look} in state ${state}`",
      "          : `unexpected end of input in state ${state}`,",
      "      );",
      "    }",
      "    if (\"shift\" in act) {",
      "      states.push(act.shift);",
      "      values.push({ token: tok!.terminal, text: tok!.text });",
      "      pos++;",
      "    } else if (\"reduce\" in act) {",
      "      const p = PRODS[act.reduce]!;",
      "      const kids = p.len === 0 ? [] : values.splice(values.length - p.len, p.len);",
      "      states.splice(states.length - p.len, p.len);",
      "      const under = states[states.length - 1]!;",
      "      const g = GOTO[under]?.[p.lhs];",
      "      if (g === undefined) throw new ParseError(\"missing goto after reduce\");",
      "      states.push(g);",
      "      values.push({ rule: act.reduce, children: kids });",
      "    } else {",
      "      return values[values.length - 1]!;",
      "    }",
      "  }",
      "}"
    ).mkString("\n")

  private val errorClass: String = "export class ParseError extends Error {}"

  // Method name per rule: its `# Label` when present and unique, else
  // `rule<id>` (always unique).
  private def methodNames(ir: IR): Map[Int, String] =
    final case class Acc(used: Set[String], out: Map[Int, String])
    val sorted = ir.grammar.rules.sortBy(_.id)
    sorted
      .foldLeft(Acc(Set.empty, Map.empty)) { (acc, r) =>
        val fallback = s"rule${r.id}"
        val preferred = r.label.getOrElse(fallback)
        val name = if acc.used.contains(preferred) then fallback else preferred
        Acc(acc.used + name, acc.out + (r.id -> name))
      }
      .out

  // The typed Visitor (D24): a method per production + `token`.
  private def visitorInterface(ir: IR): String =
    val names = methodNames(ir)
    def name(r: IRRule): String = names.getOrElse(r.id, s"rule${r.id}")
    def method(r: IRRule): String = s"  ${name(r)}(children: T[]): T;"
    "export interface Visitor<T> {\n" +
      "  token(node: CstToken): T;\n" +
      ir.grammar.rules.sortBy(_.id).map(method).mkString("\n") +
      "\n}"

  // The catamorphism: fold children bottom-up, dispatch on rule id to its method.
  private def foldFn(ir: IR): String =
    val names = methodNames(ir)
    def name(r: IRRule): String = names.getOrElse(r.id, s"rule${r.id}")
    def arm(r: IRRule): String = s"    case ${r.id}: return v.${name(r)}(kids);"
    Vector(
      "export function fold<T>(node: CstNode, v: Visitor<T>): T {",
      "  if (\"token\" in node) return v.token(node);",
      "  const kids = node.children.map((c) => fold(c, v));",
      "  switch (node.rule) {",
      ir.grammar.rules.sortBy(_.id).map(arm).mkString("\n"),
      "    default:",
      "      throw new Error(`unknown rule ${node.rule}`);",
      "  }",
      "}"
    ).mkString("\n")

  /** Emit the `<Name>.ts` implementation module. */
  def emit(ir: IR): String =
    Vector(
      banner(ir, "TypeScript recognizer + CST"),
      "",
      cstTypes,
      "",
      actionConst(ir),
      gotoConst(ir),
      prodsConst(ir),
      "",
      parseFn,
      "",
      errorClass,
      "",
      visitorInterface(ir),
      "",
      foldFn(ir)
    ).mkString("\n")

  /** Emit the `<Name>.d.ts` public type surface. */
  def emitDts(ir: IR): String =
    Vector(
      banner(ir, "TypeScript declarations"),
      "",
      cstTypes,
      "",
      "export declare function parse(tokens: Token[]): CstNode;",
      "",
      "export declare class ParseError extends Error {}",
      "",
      visitorInterface(ir),
      "",
      "export declare function fold<T>(node: CstNode, v: Visitor<T>): T;"
    ).mkString("\n")
