package gramaire

// Source-emitting codegen: generate the `lr` reduce function from the IR.
//
// `Lr.reduce` is written by hand today; here we *emit* an equivalent
// from `gramaire-ir` plus the `lr` typed-AST profile (the per-symbol
// `SemVal` constructor map). Given the profile, codegen is a pure
// function of the IR — each production becomes a case branch that
// unwraps its kids by their symbols' constructors, splices the action
// body verbatim, and wraps the result by the left-hand side's.
//
// This still emits PureScript source text (matching today's committed
// `src/Gramaire/Generated/LrReduce.purs` exactly, since the embedded
// action bodies in `grammar/lr.gram.md` are still PureScript-lambda
// syntax at this point in the port) — a Scala-emitting variant is a
// separate, later migration step (the self-hosting proof retargets both
// the actions and this codegen at Scala together).
// Ported from src/Gramaire/Codegen.purs.
object Codegen:

  /** Where the generated module is written and read back from. */
  val lrReduceModulePath: String = "src/Gramaire/Generated/LrReduce.purs"

  /** The `lr` typed-AST profile: each grammar symbol mapped to the `SemVal` constructor that
    * carries its value.
    */
  val lrConMap: Map[String, String] = Map(
    "Grammar" -> "VGrammar",
    "RuleList" -> "VRules",
    "Rule" -> "VRule",
    "Body" -> "VAlts",
    "AltTail" -> "VAlts",
    "Alt" -> "VAlt",
    "SymList" -> "VSyms",
    "Sym" -> "VSym",
    "Args" -> "VSyms",
    "Action" -> "VMaybeStr",
    "Label" -> "VMaybeStr",
    "GroupBody" -> "VGroupBody",
    "Atom" -> "VSym",
    "NotArg" -> "VSyms",
    "SetBody" -> "VSyms",
    "SetItem" -> "VSym",
    "IDENT" -> "VStr",
    "TERM_LIT" -> "VStr",
    "ACTION" -> "VStr",
    "LABEL" -> "VStr",
    "ATTR" -> "VStr"
  )

  private def termId(t: IRTerminal): Int = t match
    case IRTerminal.IRLiteral(i, _) => i
    case IRTerminal.IRClass(i, _)   => i

  private def termName(t: IRTerminal): String = t match
    case IRTerminal.IRLiteral(_, s) => s
    case IRTerminal.IRClass(_, n)   => n

  // Name lookups: a ref resolved to its symbol name, and a rule's LHS name.
  private final case class Names(ref: IRRef => String, lhs: Int => String)

  private def symbolNames(ir: IR): Names =
    val ntById: Map[Int, String] = ir.grammar.nonterminals.map(n => n.id -> n.name).toMap
    val termById: Map[Int, String] = ir.grammar.terminals.map(t => termId(t) -> termName(t)).toMap
    def look(m: Map[Int, String], i: Int): String = m.getOrElse(i, "?")
    Names(
      ref = {
        case IRRef.IRRefNT(i, _) => look(ntById, i)
        case IRRef.IRRefT(i, _)  => look(termById, i)
      },
      lhs = i => look(ntById, i)
    )

  private def actionOf(rule: IRRule): String = rule.actions.getOrElse("purescript", "")

  private final case class Lambda(params: Vector[String], body: String)

  // Split `\p1 p2 -> body` into its parameters and body text.
  private def parseLambda(s: String): Option[Lambda] =
    val trimmed = s.trim
    if !trimmed.startsWith("\\") then None
    else
      val rest = trimmed.stripPrefix("\\")
      val i = rest.indexOf("->")
      if i < 0 then None
      else
        Some(
          Lambda(
            rest.substring(0, i).trim.split(" ", -1).toVector.filter(_ != ""),
            rest.substring(i + 2).trim
          )
        )

  // A kid pattern: `_` for an ignored parameter, else `<Con> <name>`.
  private def mkPat(conMap: Map[String, String], symName: String, param: String): String =
    if param == "_" then "_" else conMap.getOrElse(symName, s"?$symName") + " " + param

  // One case branch for a production: `  <p>, [ <pats> ] -> <wrap> (<body>)`.
  private def genBranch(conMap: Map[String, String], names: Names, rule: IRRule): String =
    parseLambda(actionOf(rule)) match
      case None => s"  ${rule.id}, _ -> VErr \"no action for production ${rule.id}\""
      case Some(Lambda(params, body)) =>
        val symNames = rule.rhs.map(names.ref)
        val pats = symNames.zip(params).map { case (sn, p) => mkPat(conMap, sn, p) }
        val wrap = conMap.getOrElse(names.lhs(rule.lhs), "VErr")
        s"  ${rule.id}, [ ${pats.mkString(", ")} ] -> $wrap ($body)"

  private def header(arrayImport: Vector[String]): String =
    (Vector(
      "-- | GENERATED by Gramaire codegen from the `lr` grammar. Do not edit.",
      "-- |",
      "-- | This is the reduce `Gramaire.Lr` writes by hand, emitted from the IR",
      "-- | and the `lr` typed-AST profile. The self-host oracle (`Test.Codegen`)",
      "-- | proves it: the parser driven by this reduce reconstructs",
      "-- | `bootstrapGrammar`. Regenerate with `spago run --main",
      "-- | Gramaire.Codegen.Main`.",
      "module Gramaire.Generated.LrReduce (reduce) where",
      "",
      "import Prelude",
      ""
    ) ++ arrayImport ++ Vector(
      "import Data.Maybe (Maybe(Just, Nothing))",
      "import Gramaire.Lr (SemVal(VGrammar, VRules, VRule, VAlts, VAlt, VSyms, VSym, VGroupBody, VMaybeStr, VStr, VErr))",
      "import Gramaire.Syntax (Alt(Alt), Grammar(Grammar), Rule(Rule), Sym(Ref, Lit, Rep, Star, Opt, Macro, Field, Group, Any, Not))",
      "",
      "reduce :: Int -> Array SemVal -> SemVal",
      "reduce p kids = case p, kids of",
      ""
    )).mkString("\n")

  private val fallback: String =
    "  _, _ -> VErr (\"unexpected reduce shape for production \" <> show p)"

  /** Emit the full `Gramaire.Generated.LrReduce` module text. */
  def generateLrReduce(ir: IR): String =
    val names = symbolNames(ir)
    val body = ir.grammar.rules.map(genBranch(lrConMap, names, _)).mkString("\n")
    // Import only the Data.Array helpers the emitted reduce actually
    // uses, so the generated module stays clean under `--strict`.
    def used(name: String): Boolean = body.contains(name)
    val arrayImport: Vector[String] = (used("cons"), used("snoc")) match
      case (true, true)   => Vector("import Data.Array (cons, snoc)")
      case (true, false)  => Vector("import Data.Array (cons)")
      case (false, true)  => Vector("import Data.Array (snoc)")
      case (false, false) => Vector.empty
    header(arrayImport) + body + "\n" + fallback + "\n"
