// GENERATED by Gramark from the `Calc` grammar — PEG parser (strategy ll-star).
// Do not edit; regenerate with `gramark emit --backend scala-peg --strategy ll-star`.

object Calc:
  final case class Token(terminal: String, text: String)

  enum Cst derives CanEqual:
    case Branch(rule: Int, kids: Vector[Cst])
    case Token(terminal: String, text: String)

  def matchTerminal(toks: Vector[Token], pos: Int, label: String): Option[(Cst, Int)] =
    toks.lift(pos).filter(_.terminal == label).map(t => (Cst.Token(t.terminal, t.text), pos + 1))

  def parse_Expr(toks: Vector[Token], pos: Int): Option[(Cst, Int)] = {
    def base0: Option[(Cst, Int)] = for { (k0, p1) <- parse_Term(toks, pos) } yield (Cst.Branch(2, Vector(k0)), p1)
    base0.map { case (baseCst, basePos) =>
      @scala.annotation.tailrec
      def loop(acc: Cst, p: Int): (Cst, Int) = {
      def op0(p: Int): Option[(Cst, Int)] = for { (k0, p1) <- matchTerminal(toks, p, "+"); (k1, p2) <- parse_Term(toks, p1) } yield (Cst.Branch(0, (acc +: Vector(k0, k1))), p2)
      def op1(p: Int): Option[(Cst, Int)] = for { (k0, p1) <- matchTerminal(toks, p, "-"); (k1, p2) <- parse_Term(toks, p1) } yield (Cst.Branch(1, (acc +: Vector(k0, k1))), p2)
        op0(p).orElse(op1(p)) match {
          case None             => (acc, p)
          case Some((next, p2)) => loop(next, p2)
        }
      }
      loop(baseCst, basePos)
    }
  }

  def parse_Term(toks: Vector[Token], pos: Int): Option[(Cst, Int)] = {
    def base0: Option[(Cst, Int)] = for { (k0, p1) <- parse_Factor(toks, pos) } yield (Cst.Branch(5, Vector(k0)), p1)
    base0.map { case (baseCst, basePos) =>
      @scala.annotation.tailrec
      def loop(acc: Cst, p: Int): (Cst, Int) = {
      def op0(p: Int): Option[(Cst, Int)] = for { (k0, p1) <- matchTerminal(toks, p, "*"); (k1, p2) <- parse_Factor(toks, p1) } yield (Cst.Branch(3, (acc +: Vector(k0, k1))), p2)
      def op1(p: Int): Option[(Cst, Int)] = for { (k0, p1) <- matchTerminal(toks, p, "/"); (k1, p2) <- parse_Factor(toks, p1) } yield (Cst.Branch(4, (acc +: Vector(k0, k1))), p2)
        op0(p).orElse(op1(p)) match {
          case None             => (acc, p)
          case Some((next, p2)) => loop(next, p2)
        }
      }
      loop(baseCst, basePos)
    }
  }

  def parse_Factor(toks: Vector[Token], pos: Int): Option[(Cst, Int)] = {
    def alt0: Option[(Cst, Int)] = for { (k0, p1) <- matchTerminal(toks, pos, "("); (k1, p2) <- parse_Expr(toks, p1); (k2, p3) <- matchTerminal(toks, p2, ")") } yield (Cst.Branch(6, Vector(k0, k1, k2)), p3)
    def alt1: Option[(Cst, Int)] = for { (k0, p1) <- matchTerminal(toks, pos, "NUMBER") } yield (Cst.Branch(7, Vector(k0)), p1)
    alt0.orElse(alt1)
  }
  def parse(toks: Vector[Token]): Option[Cst] =
    parse_Expr(toks, 0).collect { case (cst, pos) if pos == toks.length => cst }

  def recognize(toks: Vector[Token]): Boolean = parse(toks).isDefined