// GENERATED by Gramark from the `Calc` grammar — fastparse PEG parser (strategy ll-star).
// Do not edit; regenerate with `gramark emit --backend scala-peg-fastparse --strategy ll-star`.

object Calc:
  import fastparse._, NoWhitespace._

  final case class Token(terminal: String, text: String)

  enum Cst derives CanEqual:
    case Branch(rule: Int, kids: Vector[Cst])
    case Token(terminal: String, text: String)

  private class Driver(tokens: Vector[Token]):
    private val termChar: Map[String, Char] =
      tokens.map(_.terminal).distinct.zipWithIndex.map { case (t, i) => t -> (0xE000 + i).toChar }.toMap
    private val input: String = tokens.map(t => termChar.getOrElse(t.terminal, '\uFFFF')).mkString

    def term[$: P](label: String): P[Cst] =
      val ch = termChar.getOrElse(label, '\uFFFF')
      // fastparse elides a Unit-typed result from a `~` chain, so `Index ~ CharPred(...)` is
      // `P[Int]`, not `P[(Int, Unit)]` — verified by actually compiling this (a tuple pattern here
      // fails with a confusing "Found: Any, Required: Int" instead of a clear arity mismatch).
      P(Index ~ CharPred(_ == ch)).map { idx =>
        Cst.Token(tokens(idx).terminal, tokens(idx).text)
      }

    def parse_Expr[$: P]: P[Cst] = P(
      ((parse_Term).map { case k0 => Cst.Branch(2, Vector(k0)) }) ~ ((((term("+") ~ parse_Term).map { case (k0, k1) => Vector(k0, k1) }).map(kids => (0, kids)) | ((term("-") ~ parse_Term).map { case (k0, k1) => Vector(k0, k1) }).map(kids => (1, kids)))).rep
    ).map { case (base, ops) =>
      def tagOp(opIdx: Int, acc: Cst, kids: Vector[Cst]): Cst = opIdx match {
              case 0 => Cst.Branch(0, (acc +: kids))
              case 1 => Cst.Branch(1, (acc +: kids))
        case other => throw new IllegalStateException(s"unknown operator index $other")
      }
      ops.foldLeft(base) { case (acc, (opIdx, kids)) => tagOp(opIdx, acc, kids) }
    }

    def parse_Term[$: P]: P[Cst] = P(
      ((parse_Factor).map { case k0 => Cst.Branch(5, Vector(k0)) }) ~ ((((term("*") ~ parse_Factor).map { case (k0, k1) => Vector(k0, k1) }).map(kids => (0, kids)) | ((term("/") ~ parse_Factor).map { case (k0, k1) => Vector(k0, k1) }).map(kids => (1, kids)))).rep
    ).map { case (base, ops) =>
      def tagOp(opIdx: Int, acc: Cst, kids: Vector[Cst]): Cst = opIdx match {
              case 0 => Cst.Branch(3, (acc +: kids))
              case 1 => Cst.Branch(4, (acc +: kids))
        case other => throw new IllegalStateException(s"unknown operator index $other")
      }
      ops.foldLeft(base) { case (acc, (opIdx, kids)) => tagOp(opIdx, acc, kids) }
    }

    def parse_Factor[$: P]: P[Cst] = P(((term("(") ~ parse_Expr ~ term(")")).map { case (k0, k1, k2) => Cst.Branch(6, Vector(k0, k1, k2)) } | (term("NUMBER")).map { case k0 => Cst.Branch(7, Vector(k0)) }))

    def parseAll: Option[Cst] =
      fastparse.parse(input, parse_Expr(using _)) match {
        case Parsed.Success(cst, idx) if idx == input.length => Some(cst)
        case _ => None
      }
    def recognizeAll: Boolean = parseAll.isDefined

  def parse(tokens: Vector[Token]): Option[Cst] = Driver(tokens).parseAll
  def recognize(tokens: Vector[Token]): Boolean = Driver(tokens).recognizeAll