// GENERATED by Gramaire from the `Calc` grammar — PEG parser (scala-parser-combinators, strategy ll-star).
// Do not edit; regenerate with `gramaire emit --backend scala-peg-combinators --strategy ll-star`.

import scala.util.parsing.combinator.Parsers
import scala.util.parsing.input.{NoPosition, Position, Reader}

object Calc extends Parsers:
  type Elem = Token
  final case class Token(terminal: String, text: String)

  enum Cst derives CanEqual:
    case Branch(rule: Int, kids: Vector[Cst])
    case Token(terminal: String, text: String)

  final case class TokenReader(tokens: Vector[Token], index: Int = 0) extends Reader[Token]:
    def first: Token = tokens(index)
    def atEnd: Boolean = index >= tokens.length
    def pos: Position = NoPosition
    def rest: Reader[Token] = TokenReader(tokens, index + 1)

  def term(label: String): Parser[Cst] =
    accept(label, { case t if t.terminal == label => Cst.Token(t.terminal, t.text) })

  def parse_Expr: Parser[Cst] = {
    val __base: Parser[Cst] = (parse_Term ^^ { k0 => Cst.Branch(2, Vector(k0)) })
    val __step: Parser[Cst => Cst] = ((term("+") ~ parse_Term) ^^ { case k0 ~ k1 => (__acc: Cst) => Cst.Branch(0, (__acc +: Vector(k0, k1))) }) | ((term("-") ~ parse_Term) ^^ { case k0 ~ k1 => (__acc: Cst) => Cst.Branch(1, (__acc +: Vector(k0, k1))) })
    (__base ~ rep(__step)) ^^ { case base ~ steps => steps.foldLeft(base) { (acc, step) => step(acc) } }
  }

  def parse_Term: Parser[Cst] = {
    val __base: Parser[Cst] = (parse_Factor ^^ { k0 => Cst.Branch(5, Vector(k0)) })
    val __step: Parser[Cst => Cst] = ((term("*") ~ parse_Factor) ^^ { case k0 ~ k1 => (__acc: Cst) => Cst.Branch(3, (__acc +: Vector(k0, k1))) }) | ((term("/") ~ parse_Factor) ^^ { case k0 ~ k1 => (__acc: Cst) => Cst.Branch(4, (__acc +: Vector(k0, k1))) })
    (__base ~ rep(__step)) ^^ { case base ~ steps => steps.foldLeft(base) { (acc, step) => step(acc) } }
  }

  def parse_Factor: Parser[Cst] = ((term("(") ~ parse_Expr ~ term(")")) ^^ { case k0 ~ k1 ~ k2 => Cst.Branch(6, Vector(k0, k1, k2)) }) | (term("NUMBER") ^^ { k0 => Cst.Branch(7, Vector(k0)) })
  def parse(toks: Vector[Token]): Option[Cst] =
    parse_Expr(TokenReader(toks)) match {
      case Success(cst, rest) if rest.atEnd => Some(cst)
      case _                                => None
    }
  def recognize(toks: Vector[Token]): Boolean = parse(toks).isDefined