// Generated by gramark --backend js for grammar "Calc-js".
// Self-contained bottom-up evaluator: each production's inline action gets a
// namedtuple of its children — an Array that also carries the `name:` fields
// as keys — so it can read a child by index (c[0]) or name (c.left), and
// destructure either way. An action-less production passes its single child
// through (else the array). `cst` is a gramark-cst JSON tree
// ({ rule, children } | { token, text }); a leaf's value is its matched text.

// production id -> action over its children namedtuple, or null
const actions = [(c) => c.expr + c.term, (c) => c.expr - c.term, null, (c) => c.term * c.factor, (c) => c.term / c.factor, null, (c) => c.expr, (c) => parseFloat(c.number)];

// production id -> field name (or null) aligned to each child position
const fields = [["expr", null, "term"], ["expr", null, "term"], ["term"], ["term", null, "factor"], ["term", null, "factor"], ["factor"], [null, "expr", null], ["number"]];

// A namedtuple: the child values as a real Array (index / spread / map all
// work) with each named position also reachable by its field name.
function tuple(values, names) {
  const t = values.slice();
  names.forEach((n, i) => { if (n != null) t[n] = values[i]; });
  return t;
}

function fold(node) {
  if (node.token !== undefined) return node.text;
  const kids = node.children.map(fold);
  const action = actions[node.rule];
  if (action) return action(tuple(kids, fields[node.rule]));
  return kids.length === 1 ? kids[0] : kids;
}

// Evaluate a gramark-cst tree to a value using the baked inline actions.
export function evaluate(cst) {
  return fold(cst);
}