// Generated by gramark --backend js for grammar "Calc-js".
// Self-contained bottom-up evaluator: each production's inline action is
// baked as a positional function over its children's values; an
// action-less production passes its single child through (else an array).
// `cst` is a gramark-cst JSON tree ({ rule, children } | { token, text });
// a leaf's value is its matched text.

// production id -> positional action over child values, or null
const actions = [(l, _, r) => l + r, (l, _, r) => l - r, null, (l, _, r) => l * r, (l, _, r) => l / r, null, (_, e, __) => e, (n) => parseFloat(n)];

function fold(node) {
  if (node.token !== undefined) return node.text;
  const kids = node.children.map(fold);
  const action = actions[node.rule];
  if (action) return action(...kids);
  return kids.length === 1 ? kids[0] : kids;
}

// Evaluate a gramark-cst tree to a value using the baked inline actions.
export function evaluate(cst) {
  return fold(cst);
}