// GENERATED by Gramaire from the `Calc` grammar — ATN recognizer (strategy ll-star).
// Do not edit; regenerate with `gramaire emit --backend atn-ts --strategy ll-star`.

type TransKind = "eps" | "atom" | "rule";
type Trans =
  | { kind: "eps"; target: number }
  | { kind: "atom"; label: string; target: number }
  | { kind: "rule"; name: string; target: number; follow: number };
type StateKind = "ruleStart" | "ruleStop" | "basic" | "blockStart" | "blockEnd";
type AtnState = {
  id: number;
  rule: string;
  kind: StateKind;
  decision: number | null;
  transitions: Trans[];
};
export type Token = { terminal: string; text: string };

type Config = { state: number; alt: number; stack: number[] };
const MAX_DEPTH = 80;

const START = 0;
const STATES: AtnState[] = [
  { id: 0, rule: "Expr", kind: "ruleStart", decision: null, transitions: [{ kind: "eps", target: 10 }] },
  { id: 1, rule: "Expr", kind: "ruleStop", decision: null, transitions: [] },
  { id: 2, rule: "Expr_tail", kind: "ruleStart", decision: null, transitions: [{ kind: "eps", target: 15 }] },
  { id: 3, rule: "Expr_tail", kind: "ruleStop", decision: null, transitions: [] },
  { id: 4, rule: "Term", kind: "ruleStart", decision: null, transitions: [{ kind: "eps", target: 27 }] },
  { id: 5, rule: "Term", kind: "ruleStop", decision: null, transitions: [] },
  { id: 6, rule: "Term_tail", kind: "ruleStart", decision: null, transitions: [{ kind: "eps", target: 32 }] },
  { id: 7, rule: "Term_tail", kind: "ruleStop", decision: null, transitions: [] },
  { id: 8, rule: "Factor", kind: "ruleStart", decision: null, transitions: [{ kind: "eps", target: 44 }] },
  { id: 9, rule: "Factor", kind: "ruleStop", decision: null, transitions: [] },
  { id: 10, rule: "Expr", kind: "blockStart", decision: 0, transitions: [{ kind: "eps", target: 12 }, { kind: "eps", target: 13 }] },
  { id: 11, rule: "Expr", kind: "blockEnd", decision: null, transitions: [{ kind: "eps", target: 1 }] },
  { id: 12, rule: "Expr", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Term", target: 4, follow: 11 }] },
  { id: 13, rule: "Expr", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Term", target: 4, follow: 14 }] },
  { id: 14, rule: "Expr", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Expr_tail", target: 2, follow: 11 }] },
  { id: 15, rule: "Expr_tail", kind: "blockStart", decision: 1, transitions: [{ kind: "eps", target: 17 }, { kind: "eps", target: 19 }, { kind: "eps", target: 22 }, { kind: "eps", target: 24 }] },
  { id: 16, rule: "Expr_tail", kind: "blockEnd", decision: null, transitions: [{ kind: "eps", target: 3 }] },
  { id: 17, rule: "Expr_tail", kind: "basic", decision: null, transitions: [{ kind: "atom", label: "+", target: 18 }] },
  { id: 18, rule: "Expr_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Term", target: 4, follow: 16 }] },
  { id: 19, rule: "Expr_tail", kind: "basic", decision: null, transitions: [{ kind: "atom", label: "+", target: 20 }] },
  { id: 20, rule: "Expr_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Term", target: 4, follow: 21 }] },
  { id: 21, rule: "Expr_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Expr_tail", target: 2, follow: 16 }] },
  { id: 22, rule: "Expr_tail", kind: "basic", decision: null, transitions: [{ kind: "atom", label: "-", target: 23 }] },
  { id: 23, rule: "Expr_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Term", target: 4, follow: 16 }] },
  { id: 24, rule: "Expr_tail", kind: "basic", decision: null, transitions: [{ kind: "atom", label: "-", target: 25 }] },
  { id: 25, rule: "Expr_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Term", target: 4, follow: 26 }] },
  { id: 26, rule: "Expr_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Expr_tail", target: 2, follow: 16 }] },
  { id: 27, rule: "Term", kind: "blockStart", decision: 2, transitions: [{ kind: "eps", target: 29 }, { kind: "eps", target: 30 }] },
  { id: 28, rule: "Term", kind: "blockEnd", decision: null, transitions: [{ kind: "eps", target: 5 }] },
  { id: 29, rule: "Term", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Factor", target: 8, follow: 28 }] },
  { id: 30, rule: "Term", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Factor", target: 8, follow: 31 }] },
  { id: 31, rule: "Term", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Term_tail", target: 6, follow: 28 }] },
  { id: 32, rule: "Term_tail", kind: "blockStart", decision: 3, transitions: [{ kind: "eps", target: 34 }, { kind: "eps", target: 36 }, { kind: "eps", target: 39 }, { kind: "eps", target: 41 }] },
  { id: 33, rule: "Term_tail", kind: "blockEnd", decision: null, transitions: [{ kind: "eps", target: 7 }] },
  { id: 34, rule: "Term_tail", kind: "basic", decision: null, transitions: [{ kind: "atom", label: "*", target: 35 }] },
  { id: 35, rule: "Term_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Factor", target: 8, follow: 33 }] },
  { id: 36, rule: "Term_tail", kind: "basic", decision: null, transitions: [{ kind: "atom", label: "*", target: 37 }] },
  { id: 37, rule: "Term_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Factor", target: 8, follow: 38 }] },
  { id: 38, rule: "Term_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Term_tail", target: 6, follow: 33 }] },
  { id: 39, rule: "Term_tail", kind: "basic", decision: null, transitions: [{ kind: "atom", label: "/", target: 40 }] },
  { id: 40, rule: "Term_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Factor", target: 8, follow: 33 }] },
  { id: 41, rule: "Term_tail", kind: "basic", decision: null, transitions: [{ kind: "atom", label: "/", target: 42 }] },
  { id: 42, rule: "Term_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Factor", target: 8, follow: 43 }] },
  { id: 43, rule: "Term_tail", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Term_tail", target: 6, follow: 33 }] },
  { id: 44, rule: "Factor", kind: "blockStart", decision: 4, transitions: [{ kind: "eps", target: 46 }, { kind: "eps", target: 49 }] },
  { id: 45, rule: "Factor", kind: "blockEnd", decision: null, transitions: [{ kind: "eps", target: 9 }] },
  { id: 46, rule: "Factor", kind: "basic", decision: null, transitions: [{ kind: "atom", label: "(", target: 47 }] },
  { id: 47, rule: "Factor", kind: "basic", decision: null, transitions: [{ kind: "rule", name: "Expr", target: 0, follow: 48 }] },
  { id: 48, rule: "Factor", kind: "basic", decision: null, transitions: [{ kind: "atom", label: ")", target: 45 }] },
  { id: 49, rule: "Factor", kind: "basic", decision: null, transitions: [{ kind: "atom", label: "NUMBER", target: 45 }] },
];

function stateAt(id: number): AtnState {
  return STATES[id]!;
}

// The ε-closure of one configuration: every configuration reachable without consuming
// input that sits at a terminal edge (an atom) or has returned to an empty call stack.
function closure(c0: Config, seedLen: number): Config[] {
  const seen = new Set<string>();
  const out: Config[] = [];
  function key(c: Config): string {
    return c.state + "|" + c.stack.join(",");
  }
  function go(c: Config): void {
    if (c.stack.length - seedLen > MAX_DEPTH) return;
    const k = key(c);
    if (seen.has(k)) return;
    seen.add(k);
    const st = stateAt(c.state);
    if (st.transitions.length === 1 && st.transitions[0]!.kind === "atom") {
      out.push(c);
      return;
    }
    if (st.transitions.length === 0) {
      if (c.stack.length === 0) {
        out.push(c);
      } else {
        const [ret, ...tail] = c.stack;
        go({ state: ret!, alt: c.alt, stack: tail });
      }
      return;
    }
    for (const t of st.transitions) {
      if (t.kind === "eps") go({ state: t.target, alt: c.alt, stack: c.stack });
      else if (t.kind === "rule")
        go({ state: t.target, alt: c.alt, stack: [t.follow, ...c.stack] });
      // a lone "atom" transition is handled by the length-1 case above; a state never
      // mixes an atom edge with any other edge (Atn's own invariant).
    }
  }
  go(c0);
  return out;
}

function closureAll(configs: Config[], seedLen: number): Config[] {
  const seen = new Set<string>();
  const out: Config[] = [];
  for (const c of configs) {
    for (const c2 of closure(c, seedLen)) {
      const k = c2.state + "#" + c2.alt + "#" + c2.stack.join(",");
      if (!seen.has(k)) {
        seen.add(k);
        out.push(c2);
      }
    }
  }
  return out;
}

// Advance a lookahead-leaf configuration over one input terminal; a configuration with no
// matching edge dies.
function move(term: string, c: Config): Config[] {
  const st = stateAt(c.state);
  const t = st.transitions[0];
  if (st.transitions.length === 1 && t !== undefined && t.kind === "atom" && t.label === term)
    return [{ ...c, state: t.target }];
  return [];
}

// The lowest (earliest-declared) alt among `configs` — first-alternative-wins on a genuine
// tie, ALL(*)'s disambiguation convention.
function uniqueAlt(configs: Config[]): number | null {
  if (configs.length === 0) return null;
  const first = configs[0]!.alt;
  let min = first;
  for (const c of configs) if (c.alt < min) min = c.alt;
  return configs.every((c) => c.alt === min) ? min : null;
}

// A configuration whose rule has run to its end with an empty call stack.
function completed(c: Config): boolean {
  return stateAt(c.state).transitions.length === 0 && c.stack.length === 0;
}

// Prefer a completed configuration over one merely pending on more input; first-alt-wins
// among whatever's left. `null` only when `configs` itself is empty.
function resolve(configs: Config[]): number | null {
  const completedConfigs = configs.filter(completed);
  const candidates = completedConfigs.length > 0 ? completedConfigs : configs;
  if (candidates.length === 0) return null;
  let min = candidates[0]!.alt;
  for (const c of candidates) if (c.alt < min) min = c.alt;
  return min;
}

// Predict the alternative to take at `decision` (a blockStart) for the input from `pos0` —
// SLL only (seed always []), no DFA cache, no full-LL retry: see the module header for why.
function predict(decision: number, input: Token[], pos0: number): number | null {
  const st = stateAt(decision);
  const starts: Config[] = st.transitions.map((t, i) =>
    t.kind === "eps"
      ? { state: t.target, alt: i, stack: [] }
      : { state: decision, alt: i, stack: [] },
  );
  let configs = closureAll(starts, 0);
  let pos = pos0;
  for (;;) {
    const u = uniqueAlt(configs);
    if (u !== null) return u;
    const tok = input[pos];
    if (tok === undefined) return resolve(configs);
    const moved = configs.flatMap((c) => move(tok.terminal, c));
    const advanced = closureAll(moved, 0);
    if (advanced.length === 0) return resolve(configs);
    configs = advanced;
    pos += 1;
  }
}

// Parse the rule whose RuleStart is `ruleStart`, from `pos`; return the position after it,
// or null if the input does not match the predicted alternative.
function parseRule(ruleStart: number, input: Token[], pos: number): number | null {
  const st = stateAt(ruleStart);
  const only = st.transitions[0];
  if (st.transitions.length !== 1 || only === undefined || only.kind !== "eps") return null;
  const blockStart = only.target;
  const i = predict(blockStart, input, pos);
  if (i === null) return null;
  const alt = stateAt(blockStart).transitions[i];
  if (alt === undefined || alt.kind !== "eps") return null;
  return walk(alt.target, input, pos);
}

// Follow one alternative's transition chain, consuming input, until its block end.
function walk(state: number, input: Token[], pos: number): number | null {
  const st = stateAt(state);
  if (st.kind === "blockEnd") return pos;
  const only = st.transitions[0];
  if (st.transitions.length !== 1 || only === undefined) return null;
  if (only.kind === "atom") {
    const tok = input[pos];
    if (tok !== undefined && tok.terminal === only.label) return walk(only.target, input, pos + 1);
    return null;
  }
  if (only.kind === "rule") {
    const result = parseRule(only.target, input, pos);
    if (result === null) return null;
    return walk(only.follow, input, result);
  }
  return walk(only.target, input, pos);
}

// Accept `input` iff the grammar's start rule recognizes the whole stream.
export function recognize(input: Token[]): boolean {
  const result = parseRule(START, input, 0);
  return result !== null && result === input.length;
}