// GENERATED by Gramark from the `Lr` grammar — TypeScript declarations.
// Do not edit; regenerate with `gramark emit --backend ts`.

export type Token = { terminal: string; text: string };
export type CstToken = { token: string; text: string };
export type CstBranch = { rule: number; children: CstNode[] };
export type CstNode = CstBranch | CstToken;

export declare function parse(tokens: Token[]): CstNode;

export declare class ParseError extends Error {}

export interface Visitor<T> {
  token(node: CstToken): T;
  rule0(children: T[]): T;
  rule1(children: T[]): T;
  rule2(children: T[]): T;
  rule3(children: T[]): T;
  rule4(children: T[]): T;
  rule5(children: T[]): T;
  rule6(children: T[]): T;
  rule7(children: T[]): T;
  rule8(children: T[]): T;
  rule9(children: T[]): T;
  rule10(children: T[]): T;
  rule11(children: T[]): T;
  rule12(children: T[]): T;
  rule13(children: T[]): T;
  rule14(children: T[]): T;
  rule15(children: T[]): T;
  rule16(children: T[]): T;
  rule17(children: T[]): T;
  rule18(children: T[]): T;
  rule19(children: T[]): T;
  rule20(children: T[]): T;
  rule21(children: T[]): T;
  rule22(children: T[]): T;
  rule23(children: T[]): T;
  rule24(children: T[]): T;
  rule25(children: T[]): T;
  rule26(children: T[]): T;
  rule27(children: T[]): T;
  rule28(children: T[]): T;
  rule29(children: T[]): T;
  rule30(children: T[]): T;
  rule31(children: T[]): T;
  rule32(children: T[]): T;
  rule33(children: T[]): T;
  rule34(children: T[]): T;
  rule35(children: T[]): T;
  rule36(children: T[]): T;
  rule37(children: T[]): T;
  rule38(children: T[]): T;
  rule39(children: T[]): T;
  rule40(children: T[]): T;
  rule41(children: T[]): T;
  rule42(children: T[]): T;
  rule43(children: T[]): T;
  rule44(children: T[]): T;
  rule45(children: T[]): T;
  rule46(children: T[]): T;
  rule47(children: T[]): T;
  rule48(children: T[]): T;
  rule49(children: T[]): T;
  rule50(children: T[]): T;
  rule51(children: T[]): T;
  rule52(children: T[]): T;
  rule53(children: T[]): T;
}

export declare function fold<T>(node: CstNode, v: Visitor<T>): T;