// GENERATED by Grammark from the `Lr` grammar — TypeScript declarations.
// Do not edit; regenerate with `grammark emit --backend ts`.

export type Token = { terminal: string; text: string };
export type CstToken = { token: string; text: string };
export type CstBranch = { rule: number; children: CstNode[] };
export type CstNode = CstBranch | CstToken;

export declare function parse(tokens: Token[]): CstNode;

export declare class ParseError extends Error {}

export interface Visitor<T> {
  token(node: CstToken): T;
  rule0(children: T[]): T;
  rule1(children: T[]): T;
  rule2(children: T[]): T;
  rule3(children: T[]): T;
  rule4(children: T[]): T;
  rule5(children: T[]): T;
  rule6(children: T[]): T;
  rule7(children: T[]): T;
  rule8(children: T[]): T;
  rule9(children: T[]): T;
  rule10(children: T[]): T;
  rule11(children: T[]): T;
  rule12(children: T[]): T;
  rule13(children: T[]): T;
  rule14(children: T[]): T;
  rule15(children: T[]): T;
  rule16(children: T[]): T;
  rule17(children: T[]): T;
  rule18(children: T[]): T;
  rule19(children: T[]): T;
  rule20(children: T[]): T;
  rule21(children: T[]): T;
  rule22(children: T[]): T;
  rule23(children: T[]): T;
  rule24(children: T[]): T;
  rule25(children: T[]): T;
  rule26(children: T[]): T;
  rule27(children: T[]): T;
}

export declare function fold<T>(node: CstNode, v: Visitor<T>): T;