-- | A backend that bakes a grammar's inline `{% … %}` JavaScript actions into a
-- | single self-contained ES module. With `%lang javascript` declared, each
-- | production's action is host source carried verbatim; the backend folds a
-- | `gramark-cst` JSON tree bottom-up, handing each action a **namedtuple** of
-- | its children — a plain `Array` that also carries the production's `name:`
-- | fields as keys. So an action can read a child by index or by name, and
-- | destructure either way:
-- |
-- |   left:Expr '+' right:Term  {% (c) => c.left + c.right %}
-- |                             {% ({ left, right }) => left + right %}
-- |                             {% (c) => c[0] + c[2] %}
-- |
-- | An action-less production passes its single child through (else the array of
-- | children). This is the `Actions "js"` capability, and the module the Lab runs.
module Gramark.Backend.Js
  ( backend
  , emit
  ) where

import Prelude

import Data.Array as Array
import Data.Maybe (Maybe(..))
import Data.String (Pattern(..), drop, indexOf, joinWith, stripPrefix, trim)
import Data.String.CodeUnits (singleton, toCharArray)
import Data.Tuple (Tuple(..), snd)
import Gramark.Backend (Backend, Capability(..), allStrategies)
import Gramark.IR (IR, IRRule, effectiveFields)

-- | The JS backend: one `<Name>.js` ES module exposing `evaluate(cst)`.
backend :: Backend
backend =
  { name: "js"
  , capabilities: [ Actions "js" ]
  , strategies: allStrategies
  , emit: \ir -> [ { path: ir.grammar.name <> ".js", contents: emit ir } ]
  }

-- | Render the evaluator module: the per-production action table (each slot the
-- | verbatim inline action, or `null`), the aligned field-name table (for the
-- | namedtuple), and the fixed folding runtime.
emit :: IR -> String
emit ir =
  joinWith "\n"
    [ "// Generated by gramark --backend js for grammar " <> jsStr ir.grammar.name <> "."
    , "// Self-contained bottom-up evaluator: each production's inline action gets a"
    , "// namedtuple of its children — an Array that also carries the `name:` fields"
    , "// as keys — so it can read a child by index (c[0]) or name (c.left), and"
    , "// destructure either way. An action-less production passes its single child"
    , "// through (else the array). `cst` is a gramark-cst JSON tree"
    , "// ({ rule, children } | { token, text }); a leaf's value is its matched text."
    , ""
    , "// production id -> action over its children namedtuple, or null"
    , "const actions = [" <> joinWith ", " (map actionSlot ir.grammar.rules) <> "];"
    , ""
    , "// production id -> field name (or null) aligned to each child position"
    , "const fields = [" <> joinWith ", " (map fieldSlot ir.grammar.rules) <> "];"
    , ""
    , runtime
    ]
  where
  actionSlot :: IRRule -> String
  actionSlot r = case jsAction r of
    Just code -> code
    Nothing -> "null"

  fieldSlot :: IRRule -> String
  fieldSlot r = "[" <> joinWith ", " (map maybeStr (effectiveFields ir.grammar r)) <> "]"

-- The `js`-tagged inline action for a rule, if any, as the user's own function.
-- The front end stores actions under their host-language profile (see
-- `IR.withActionLang`); the JS backend only bakes the ones tagged `js`, so it
-- never emits foreign code.
jsAction :: IRRule -> Maybe String
jsAction r = unwrapBinder <<< snd <$> Array.find (\(Tuple profile _) -> profile == "js") r.actions

maybeStr :: Maybe String -> String
maybeStr = case _ of
  Just s -> jsStr s
  Nothing -> "null"

-- `Desugar.normalizeAction` wraps a bare action body in a PureScript binder
-- `\params -> body` so PureScript codegen can bind the children. For a JS host
-- that wrapper is inert: the user's action is already a complete function over
-- the namedtuple. Recover it by dropping the synthesized binder — the wrapper's
-- arrow is ` -> ` while a JS arrow is `=>`, so the first ` -> ` always ends the
-- binder. A body that was not wrapped (does not start with `\`) is unchanged.
unwrapBinder :: String -> String
unwrapBinder code = case stripPrefix (Pattern "\\") (trim code) of
  Nothing -> trim code
  Just _ -> case indexOf (Pattern " -> ") code of
    Just i -> trim (drop (i + 4) code)
    Nothing -> trim code

-- The fixed runtime: a bottom-up fold where a leaf evaluates to its matched
-- text, and a production with an action applies it to the namedtuple of its
-- children (an Array with the `name:` fields attached as keys). An action-less
-- production passes a lone child through (else returns the array).
runtime :: String
runtime =
  joinWith "\n"
    [ "// A namedtuple: the child values as a real Array (index / spread / map all"
    , "// work) with each named position also reachable by its field name."
    , "function tuple(values, names) {"
    , "  const t = values.slice();"
    , "  names.forEach((n, i) => { if (n != null) t[n] = values[i]; });"
    , "  return t;"
    , "}"
    , ""
    , "function fold(node) {"
    , "  if (node.token !== undefined) return node.text;"
    , "  const kids = node.children.map(fold);"
    , "  const action = actions[node.rule];"
    , "  if (action) return action(tuple(kids, fields[node.rule]));"
    , "  return kids.length === 1 ? kids[0] : kids;"
    , "}"
    , ""
    , "// Evaluate a gramark-cst tree to a value using the baked inline actions."
    , "export function evaluate(cst) {"
    , "  return fold(cst);"
    , "}"
    ]

-- A JS string literal (double-quoted), escaping the characters that matter.
jsStr :: String -> String
jsStr s = "\"" <> joinWith "" (map esc (toCharArray s)) <> "\""
  where
  esc c = case c of
    '"' -> "\\\""
    '\\' -> "\\\\"
    '\n' -> "\\n"
    _ -> singleton c
