-- | A backend that bakes a grammar's inline `{% … %}` JavaScript actions into a
-- | single self-contained ES module. With `%lang javascript` declared (ADR: the
-- | `## General settings` block), each production's action is host source carried
-- | verbatim — and since an action like `(l, _, r) => l + r` already *is* a
-- | positional function over its children, the backend can drop it straight into
-- | a per-production table and fold a `gramark-cst` JSON tree against it.
-- |
-- | The emitted module is the one source of truth for evaluation — the Lab runs
-- | exactly this `evaluate(cst)` (no second hand-written fold). A production with
-- | no `js`-tagged action passes its single child through (else yields the array
-- | of children), so an unannotated or non-JS grammar still evaluates structurally
-- | rather than erroring. This is the `Actions "js"` capability.
module Gramark.Backend.Js
  ( backend
  , emit
  ) where

import Prelude

import Data.Array as Array
import Data.Maybe (Maybe(..))
import Data.String (Pattern(..), drop, indexOf, joinWith, stripPrefix, trim)
import Data.String.CodeUnits (singleton, toCharArray)
import Data.Tuple (Tuple(..), snd)
import Gramark.Backend (Backend, Capability(..), allStrategies)
import Gramark.IR (IR, IRRule)

-- | The JS backend: one `<Name>.js` ES module exposing `evaluate(cst)`.
backend :: Backend
backend =
  { name: "js"
  , capabilities: [ Actions "js" ]
  , strategies: allStrategies
  , emit: \ir -> [ { path: ir.grammar.name <> ".js", contents: emit ir } ]
  }

-- | Render the evaluator module: the per-production action table (each slot the
-- | verbatim inline action, or `null`) and the fixed folding runtime.
emit :: IR -> String
emit ir =
  joinWith "\n"
    [ "// Generated by gramark --backend js for grammar " <> jsStr ir.grammar.name <> "."
    , "// Self-contained bottom-up evaluator: each production's inline action is"
    , "// baked as a positional function over its children's values; an"
    , "// action-less production passes its single child through (else an array)."
    , "// `cst` is a gramark-cst JSON tree ({ rule, children } | { token, text });"
    , "// a leaf's value is its matched text."
    , ""
    , "// production id -> positional action over child values, or null"
    , "const actions = [" <> joinWith ", " (map actionSlot ir.grammar.rules) <> "];"
    , ""
    , runtime
    ]
  where
  actionSlot :: IRRule -> String
  actionSlot r = case jsAction r of
    Just code -> code
    Nothing -> "null"

-- The `js`-tagged inline action for a rule, if any, as the user's own arrow. The
-- front end stores actions under their host-language profile (see
-- `IR.withActionLang`); the JS backend only bakes the ones tagged `js`, so it
-- never emits foreign code.
jsAction :: IRRule -> Maybe String
jsAction r = unwrapBinder <<< snd <$> Array.find (\(Tuple profile _) -> profile == "js") r.actions

-- `Desugar.normalizeAction` wraps a bare action body in a PureScript binder
-- `\params -> body` so PureScript codegen can bind the children. For a JS host
-- that wrapper is inert: the user's action is already a complete arrow. Recover
-- it by dropping the synthesized binder — the wrapper's arrow is ` -> ` while a
-- JS arrow is `=>`, so the first ` -> ` always ends the binder. A body that was
-- not wrapped (does not start with `\`) is returned unchanged.
unwrapBinder :: String -> String
unwrapBinder code = case stripPrefix (Pattern "\\") (trim code) of
  Nothing -> trim code
  Just _ -> case indexOf (Pattern " -> ") code of
    Just i -> trim (drop (i + 4) code)
    Nothing -> trim code

-- The fixed runtime: a bottom-up fold where a leaf evaluates to its matched
-- text, a production with an action applies it to its children positionally, and
-- an action-less production passes a lone child through (else returns the array).
runtime :: String
runtime =
  joinWith "\n"
    [ "function fold(node) {"
    , "  if (node.token !== undefined) return node.text;"
    , "  const kids = node.children.map(fold);"
    , "  const action = actions[node.rule];"
    , "  if (action) return action(...kids);"
    , "  return kids.length === 1 ? kids[0] : kids;"
    , "}"
    , ""
    , "// Evaluate a gramark-cst tree to a value using the baked inline actions."
    , "export function evaluate(cst) {"
    , "  return fold(cst);"
    , "}"
    ]

-- A JS string literal (double-quoted), escaping the characters that matter.
jsStr :: String -> String
jsStr s = "\"" <> joinWith "" (map esc (toCharArray s)) <> "\""
  where
  esc c = case c of
    '"' -> "\\\""
    '\\' -> "\\\\"
    '\n' -> "\\n"
    _ -> singleton c
