/* eslint-disable */
/**
 * This file was automatically generated by site/scripts/gen-lab-types.mjs
 * from spec/lab-protocol-schema.json. Do not edit by hand — run
 * `npm run gen:lab-types` (from site/) instead.
 */

/**
 * Which table-construction method to build with — mirrors gramark.Method exactly.
 */
export type Method = "Canonical" | "LALR" | "IELR";

/**
 * A request from the Lab UI: the full .grmk.md source, an optional target-language input to parse, and the table-construction method to build with. Omitting `input` (or sending null) means compile-only.
 */
export interface LabRequest {
  source: string;
  input?: string | null;
  method: Method;
  /**
   * The rule to treat as the grammar's start/entry rule, overriding the default of the first declared rule. Null (or omitted) means use the grammar's own declaration order, exactly like every non-Lab caller (the CLI, core test suites).
   */
  startRule?: string | null;
}

/**
 * The same node shape as cst-schema.json's $defs/node (Cst.toJson emits it identically here, just embedded as ParseResult.cst instead of wrapped in the {cstVersion, root} envelope that artifact's own top level adds) — kept in sync by hand, both schemas are hand-authored from the same Cst.scala encoder.
 */
export type CstNode = CstBranch | CstToken;
/**
 * A kind-tagged LR action.
 */
export type LrActionInfo =
  | {
      kind: "shift";
      terminal: string;
      lexeme: string;
    }
  | {
      kind: "reduce";
      lhs: string;
      rhs: string[];
      prodIndex: number;
    }
  | {
      kind: "accept";
    };

/**
 * The Lab's full response: whether the grammar itself built, any diagnostics, and — if input was given and the grammar built — the parse result.
 */
export interface LabResponse {
  /**
   * The current protocol version — must equal LabProtocol.scala's LabResponse.version. `default`, a standard/ajv-strict-mode-safe JSON Schema keyword, not `const`: a `const` would narrow the generated LabResponse.labProtocolVersion TS field to the literal type `1`, breaking site/src/lab/worker.ts's staleEngineResponse, which deliberately reports a DIFFERENT, mismatched version number as diagnostic data — the type still needs to stay a plain `number`. gen-lab-types.mjs reads this `default` to emit a LAB_PROTOCOL_VERSION constant into protocol.ts, the single source of truth worker.ts's stale-engine-bundle guard derives from instead of a second hand-maintained literal that could drift from LabResponse.version independently. Bump both together on any breaking wire-format change.
   */
  labProtocolVersion: number;
  /**
   * True iff the grammar compiled and its tables built with no unresolved conflicts. When false, `diagnostics` names why and `parse` is always null.
   */
  buildOk: boolean;
  /**
   * Errors (a grammar-notation lexical/parse/undefined-nonterminal failure, or a table conflict) when buildOk is false, plus warnings (an unknown #[attr]/%setting, an unreachable rule, an unused token class) either way — distinguish by each entry's own `severity`.
   */
  diagnostics: DiagnosticInfo[];
  /**
   * Present only when the request carried `input` and the grammar built successfully; null otherwise (compile-only requests, or any build failure).
   */
  parse: ParseResult | null;
  /**
   * The Lowered Core tab's data: every flattened production of the desugared grammar. Present whenever the grammar notation parsed (Lr.parse succeeded), independent of buildOk — a grammar with genuine LR conflicts still has a well-defined production list. Null only when the grammar notation itself failed to parse.
   */
  productions: ProductionInfo[] | null;
  /**
   * The All-parses tab's data: every distinct parse of `input` under the GLR multi-action table, which never fails even when the grammar has real conflicts under every method (that's exactly the ambiguous-grammar case this tab exists for, so `forest` can be populated even when buildOk is false). Present only when the request carried `input` and the grammar notation parsed; null otherwise.
   */
  forest: ForestResult | null;
  /**
   * The Grammar analysis tab's data: every method's state/conflict count, FIRST/FOLLOW per rule, and a railroad SVG per rule. Present whenever the grammar notation parsed, independent of buildOk (same reasoning as `productions`); null only when the grammar notation itself failed to parse.
   */
  analysis: GrammarAnalysis | null;
  /**
   * The Evaluate tab's data: BackendJs.emitTraced's generated ES module source text, run by the Worker (not this schema's owner — Scala never executes it). Present only when buildOk is true (it needs a valid compiled table); null otherwise.
   */
  evaluatorJs: string | null;
}
/**
 * One structured diagnostic: a severity, which pipeline stage raised it, a message, an optional source span, free-form note/help lines, and a plain-text rendering (the same caret-framed text the CLI prints) as a display fallback.
 */
export interface DiagnosticInfo {
  severity: "error" | "warning";
  stage: "lex" | "parse" | "desugar" | "resolve" | "tables" | "internal";
  message: string;
  span: SrcSpanInfo | null;
  /**
   * Free-form note/help lines, e.g. "help: did you mean `Factor`?" — the tag is part of the text.
   */
  notes: string[];
  /**
   * The plain-text rendering (Diagnostic.render): a headline, an optional --> name:line:col location with a caret-underlined source line, then the notes — the same text the CLI prints.
   */
  rendered: string;
}
/**
 * A `[start, end)` code-unit span into whichever source text the owning Diagnostic is relative to (the grammar source, or LabRequest.input).
 */
export interface SrcSpanInfo {
  start: number;
  end: number;
}
/**
 * The outcome of parsing LabRequest.input against the compiled grammar. `tokens` is populated even on a reject, so the Tokens tab still has something to show; `cst`/`trace` are null unless `accepted`.
 */
export interface ParseResult {
  accepted: boolean;
  /**
   * The reject reason (a located lexical or parse diagnostic, relative to LabRequest.input) when accepted is false; null when accepted.
   */
  message: DiagnosticInfo | null;
  tokens: LabToken[];
  cst: CstNode | null;
  /**
   * The Parse trace / LR walk tabs' data: the full shift/reduce/accept sequence, one entry per step. Present only when accepted.
   */
  trace: LrStepInfo[] | null;
}
/**
 * A single lexed token from the Lab's Tokens tab, with its source span (start/end are code-unit offsets into LabRequest.input, [start, end) — matching gramark.Spanned's own convention).
 */
export interface LabToken {
  text: string;
  terminal: string;
  start: number;
  end: number;
}
export interface CstBranch {
  rule: number;
  children: CstNode[];
}
export interface CstToken {
  token: string;
  text: string;
}
/**
 * One step of an LR walk: the action taken and the parse stack/remaining-input state before taking it.
 */
export interface LrStepInfo {
  index: number;
  stateBefore: number;
  action: LrActionInfo;
  /**
   * Bottom to top, before this action; already display-rendered like ProductionInfo.rhs.
   */
  stackSymbols: string[];
  /**
   * Before this action, including a trailing `$` EOF marker.
   */
  remainingSymbols: string[];
}
/**
 * One flattened production of the compiled grammar. `lhs`/`rhs` are already display-rendered (a terminal is backtick-quoted, e.g. `` `+` ``; a nonterminal is bare).
 */
export interface ProductionInfo {
  lhs: string;
  rhs: string[];
  /**
   * The production's raw `{% … %}` action source text, or null when the alternative has no action.
   */
  action: string | null;
}
/**
 * Every distinct parse of the target input, capped so a wildly ambiguous grammar can't blow up the response.
 */
export interface ForestResult {
  parses: CstNode[];
  /**
   * True when more distinct parses existed than `parses` holds.
   */
  truncated: boolean;
}
/**
 * Every method's state/conflict count (not just the requested method, so the tab can render the three-method comparison without a re-request), FIRST/FOLLOW per rule, and a railroad SVG per rule, built from the compiled grammar directly.
 */
export interface GrammarAnalysis {
  /**
   * Keyed by method name ("Canonical" | "LALR" | "IELR").
   */
  perMethod: {
    [k: string]: MethodStatsInfo;
  };
  firstFollow: RuleFirstFollow[];
  /**
   * Keyed by rule name; each value is a self-contained SVG string.
   */
  railroad: {
    [k: string]: string;
  };
}
/**
 * One table-construction method's automaton size and conflict count.
 */
export interface MethodStatsInfo {
  states: number;
  conflicts: number;
}
/**
 * One nonterminal's FIRST/FOLLOW sets, display-rendered like ProductionInfo.rhs (a terminal backtick-quoted, EOF as `$`).
 */
export interface RuleFirstFollow {
  name: string;
  first: string[];
  follow: string[];
}

export const LAB_PROTOCOL_VERSION = 1;
