/* eslint-disable */
/**
 * This file was automatically generated by site/scripts/gen-lab-types.mjs
 * from spec/lab-protocol-schema.json. Do not edit by hand — run
 * `npm run gen:lab-types` (from site/) instead.
 */

/**
 * Which table-construction method to build with — mirrors gramaire.Method exactly.
 */
export type Method = "Canonical" | "LALR" | "IELR";
/**
 * Which parse strategy to build under — mirrors gramaire.IR's two D-strategy values. "lr" is the table-driven LR/GLR pipeline. "ll-star" is the ALL(*) port (Ll.parseTraced): parse/evaluatorJs/atn are driven by it instead — buildOk no longer depends on the LR table build succeeding (a conflict downgrades to a warning), parse.trace is always absent in favor of parse.llTrace, and evaluatorJs generates even when the grammar has real LR conflicts (it needs no table build). forest/analysis stay LR/GLR-driven under both strategies — method always selects the automaton they're built from.
 */
export type Strategy = "lr" | "ll-star";
/**
 * Which railroad diagram view to render — mirrors gramaire.Railroad.DiagramView exactly. "source" is byte-faithful to the authored grammar, the historical stacked-track layout. "simplified" recognizes a couple of safe idioms (DiagramNormalize: an optional tail, a direct-left-recursive repetition chain) and applies width-aware wrapping for long sequences.
 */
export type DiagramView = "source" | "simplified";

/**
 * A request from the Lab UI: the full .gram.md source, an optional target-language input to parse, and the table-construction method to build with. Omitting `input` (or sending null) means compile-only.
 */
export interface LabRequest {
  source: string;
  input?: string | null;
  method: Method;
  /**
   * The rule to treat as the grammar's start/entry rule, overriding the default of the first declared rule. Null (or omitted) means use the grammar's own declaration order, exactly like every non-Lab caller (the CLI, core test suites).
   */
  startRule?: string | null;
  /**
   * Which parse strategy to build under. Null (or omitted) means "lr", the table-driven pipeline. "ll-star" is a genuine alternate pipeline for parse/evaluatorJs/atn (see the `strategy` def's own description) — forest/analysis stay LR/GLR-driven either way.
   */
  strategy?: Strategy | null;
  /**
   * Which railroad diagram view `analysis.railroad` renders in. Null (or omitted) means "source", byte-faithful to the authored grammar. "simplified" recognizes a couple of safe idioms (an optional tail, a direct-left-recursive repetition chain) and applies width-aware wrapping — see the `diagramView` def's own description, mirroring gramaire.Railroad.DiagramView.
   */
  diagramView?: DiagramView | null;
}

/**
 * The same node shape as cst-schema.json's $defs/node (Cst.toJson emits it identically here, just embedded as ParseResult.cst instead of wrapped in the {cstVersion, root} envelope that artifact's own top level adds) — kept in sync by hand, both schemas are hand-authored from the same Cst.scala encoder.
 */
export type CstNode = CstBranch | CstToken;
/**
 * A kind-tagged LR action.
 */
export type LrActionInfo =
  | {
      kind: "shift";
      terminal: string;
      lexeme: string;
    }
  | {
      kind: "reduce";
      lhs: string;
      rhs: string[];
      prodIndex: number;
    }
  | {
      kind: "accept";
    };
/**
 * A kind-tagged ALL(*) walk action, mirroring LrActionInfo's shape.
 */
export type LlActionInfo =
  | {
      kind: "predict";
      /**
       * The rule the walk actually descends — a LeftRec-folded tail rule or PrecClimb-stratified level, not the original grammar rule an alt may fold back to on the Cst.
       */
      rule: string;
      chosenAlt: number;
      altCount: number;
    }
  | {
      kind: "match";
      terminal: string;
      lexeme: string;
    }
  | {
      kind: "exitRule";
      rule: string;
    }
  | {
      kind: "accept";
    };
/**
 * How a rendered grammar symbol should be classified for display: a quoted string literal, a named lexical token, a nonterminal (a rule reference), or the end-of-input marker.
 */
export type SymbolKind = "literal" | "token" | "nonterminal" | "eof";

/**
 * The Lab's full response: whether the grammar itself built, any diagnostics, and — if input was given and the grammar built — the parse result.
 */
export interface LabResponse {
  /**
   * The current protocol version — must equal LabProtocol.scala's LabResponse.version. `default`, a standard/ajv-strict-mode-safe JSON Schema keyword, not `const`: a `const` would narrow the generated LabResponse.labProtocolVersion TS field to the literal type `1`, breaking site/src/lab/worker.ts's staleEngineResponse, which deliberately reports a DIFFERENT, mismatched version number as diagnostic data — the type still needs to stay a plain `number`. gen-lab-types.mjs reads this `default` to emit a LAB_PROTOCOL_VERSION constant into protocol.ts, the single source of truth worker.ts's stale-engine-bundle guard derives from instead of a second hand-maintained literal that could drift from LabResponse.version independently. Bump both together on any breaking wire-format change.
   */
  labProtocolVersion: number;
  /**
   * Under strategy "lr": true iff the grammar compiled and its LR tables built with no unresolved conflicts; when false, `diagnostics` names why and `parse` is always null. Under strategy "ll-star": true whenever the grammar notation itself parsed and desugared — an LR conflict no longer blocks the build, it only appears in `diagnostics` as a warning, since ALL(*) resolves the same tie itself, by declaration order.
   */
  buildOk: boolean;
  /**
   * Errors (a grammar-notation lexical/parse/undefined-nonterminal failure, or a table conflict) when buildOk is false, plus warnings (an unknown #[attr]/%setting, an unreachable rule, an unused token class) either way — distinguish by each entry's own `severity`.
   */
  diagnostics: DiagnosticInfo[];
  /**
   * Present only when the request carried `input` and the grammar built successfully; null otherwise (compile-only requests, or any build failure).
   */
  parse: ParseResult | null;
  /**
   * The Lowered Core tab's data: every flattened production of the desugared grammar. Present whenever the grammar notation parsed (Lr.parse succeeded), independent of buildOk — a grammar with genuine LR conflicts still has a well-defined production list. Null only when the grammar notation itself failed to parse.
   */
  productions: ProductionInfo[] | null;
  /**
   * The All-parses tab's data: every distinct parse of `input` under the GLR multi-action table, which never fails even when the grammar has real conflicts under every method (that's exactly the ambiguous-grammar case this tab exists for, so `forest` can be populated even when buildOk is false). Present only when the request carried `input` and the grammar notation parsed; null otherwise.
   */
  forest: ForestResult | null;
  /**
   * The Grammar analysis tab's data: every method's state/conflict count, FIRST/FOLLOW per rule, and a railroad SVG per rule. Present whenever the grammar notation parsed, independent of buildOk (same reasoning as `productions`); null only when the grammar notation itself failed to parse.
   */
  analysis: GrammarAnalysis | null;
  /**
   * The Evaluate tab's data: BackendJs.emitTraced's generated ES module source text, run by the Worker (not this schema's owner — Scala never executes it). Needs no LR table build (it reads only the grammar's structure), so it's present whenever buildOk is true under EITHER strategy — including an ll-star build with a downgraded-to-warning LR conflict; null otherwise, or if the grammar declares a `{%? %}` predicate (neither runtime evaluates predicates yet).
   */
  evaluatorJs: string | null;
  /**
   * The ATN diagnostics tab's data, under strategy "ll-star": whether Ll.parseTraced accepts `input` (mirrors `parse.accepted`), the DFA prediction cache's hit/miss counts, and every declaration-order-resolved ambiguity hit along the way — from the SAME cache run that produced `parse`, not a separate one. Present only when the request's strategy is "ll-star" and `input` is given.
   */
  atn: AtnDiagnostics | null;
  /**
   * The Lowered Core tab's ALL(*)-only section: the same precedence-stratification and left-recursion-elimination rewrite Ll.parse/Ll.parseTraced run before lowering to an ATN, independent of which Engine/strategy the request selected (same reasoning as `productions`/`analysis`). Present whenever `productions` is; null only when the grammar notation itself failed to parse.
   */
  allStarLowering: AllStarLowering | null;
  /**
   * The Live Document notebook's per-fence role + line span, in document order. Computed directly from LabRequest.source's own raw text, independent of whether the grammar notation parses (Lr.classifyFenceContent's "case is law" classification is pure content shape) — a broken grammar still shows correct cell boundaries/role badges to fix it by. Empty for a fence-free native .gram source.
   */
  fences: FenceInfo[];
  /**
   * The grammar's own declared name (ADR D58: Lr.nameOf, frontmatter-first with a dual-read fallback to the deprecated fenced `name:` settings block). Read independent of whether the grammar notation parses (same reasoning as `fences`) — null only when neither a frontmatter block nor the old fence declares one. The Notebook's own download-filename logic consumes this instead of re-deriving it client-side.
   */
  name: string | null;
}
/**
 * One structured diagnostic: a severity, which pipeline stage raised it, a message, an optional source span, free-form note/help lines, and a plain-text rendering (the same caret-framed text the CLI prints) as a display fallback.
 */
export interface DiagnosticInfo {
  severity: "error" | "warning";
  stage: "lex" | "parse" | "desugar" | "resolve" | "tables" | "internal";
  message: string;
  span: SrcSpanInfo | null;
  /**
   * Free-form note/help lines, e.g. "help: did you mean `Factor`?" — the tag is part of the text.
   */
  notes: string[];
  /**
   * The plain-text rendering (Diagnostic.render): a headline, an optional --> name:line:col location with a caret-underlined source line, then the notes — the same text the CLI prints.
   */
  rendered: string;
}
/**
 * A `[start, end)` code-unit span into whichever source text the owning Diagnostic is relative to (the grammar source, or LabRequest.input).
 */
export interface SrcSpanInfo {
  start: number;
  end: number;
}
/**
 * The outcome of parsing LabRequest.input against the compiled grammar. `tokens` is populated even on a reject, so the Tokens tab still has something to show; `cst` is null unless `accepted`. `trace` (strategy "lr") and `llTrace` (strategy "ll-star") are mutually exclusive — exactly one of the two is ever non-null, matching LabRequest.strategy — and both share `cst`'s accepted-only lifecycle.
 */
export interface ParseResult {
  accepted: boolean;
  /**
   * The reject reason (a located lexical or parse diagnostic, relative to LabRequest.input) when accepted is false; null when accepted.
   */
  message: DiagnosticInfo | null;
  tokens: LabToken[];
  cst: CstNode | null;
  /**
   * The Parse trace / LR walk tabs' data under strategy "lr": the shift/reduce/accept sequence, one entry per step, capped at LabApi's traceCap. Present only when accepted.
   */
  trace: LrStepInfo[] | null;
  /**
   * True when the real walk had more steps than `trace` holds (LabApi's traceCap).
   */
  traceTruncated: boolean;
  /**
   * The Parse trace / LL walk tabs' data under strategy "ll-star": the predict/match/exitRule/accept sequence, one entry per step, capped at LabApi's traceCap. Present only when accepted.
   */
  llTrace: LlStepInfo[] | null;
  /**
   * True when the real walk had more steps than `llTrace` holds (LabApi's traceCap).
   */
  llTraceTruncated: boolean;
}
/**
 * A single lexed token from the Lab's Tokens tab, with its source span (start/end are code-unit offsets into LabRequest.input, [start, end) — matching gramaire.Spanned's own convention).
 */
export interface LabToken {
  text: string;
  terminal: string;
  start: number;
  end: number;
}
export interface CstBranch {
  rule: number;
  children: CstNode[];
}
export interface CstToken {
  token: string;
  text: string;
}
/**
 * One step of an LR walk: the action taken and the parse stack/remaining-input state before taking it.
 */
export interface LrStepInfo {
  index: number;
  stateBefore: number;
  action: LrActionInfo;
  /**
   * Bottom to top, before this action; plain backtick-quoted display text (a terminal is backtick-quoted, e.g. `` `+` ``; a nonterminal is bare) — unlike ProductionInfo.rhs/RuleFirstFollow, this walk trace has no client need for kind classification yet, so it stays string-only.
   */
  stackSymbols: string[];
  /**
   * Before this action, including a trailing `$` EOF marker.
   */
  remainingSymbols: string[];
}
/**
 * One step of an ALL(*) walk: the `lr` walk's ll-star counterpart. `ruleStack` is bottom to top, including the rule the action concerns.
 */
export interface LlStepInfo {
  index: number;
  /**
   * Bottom to top, before this action — a (possibly LeftRec/PrecClimb-rewritten) rule name per frame.
   */
  ruleStack: string[];
  action: LlActionInfo;
  pos: number;
}
/**
 * One flattened production of the compiled grammar. `lhs` is the bare nonterminal name; `rhs` is each right-hand-side symbol classified via RenderedSymbol.
 */
export interface ProductionInfo {
  lhs: string;
  rhs: RenderedSymbol[];
  /**
   * The production's raw `{% … %}` action source text, or null when the alternative has no action.
   */
  action: string | null;
}
/**
 * A single grammar symbol as displayed text plus its kind, so a client can style literals/tokens/nonterminals/EOF differently without re-parsing the rendered text (e.g. a literal is never backtick-quoted; a token or literal previously couldn't be told apart from the text alone).
 */
export interface RenderedSymbol {
  text: string;
  kind: SymbolKind;
}
/**
 * Every distinct parse of the target input, capped so a wildly ambiguous grammar can't blow up the response.
 */
export interface ForestResult {
  parses: CstNode[];
  /**
   * True when more distinct parses existed than `parses` holds.
   */
  truncated: boolean;
}
/**
 * Every method's state/conflict count (not just the requested method, so the tab can render the three-method comparison without a re-request), FIRST/FOLLOW per rule, a railroad SVG per rule, the conflict-classification verdict, and the grammar's terminal/nonterminal/start-symbol summary, built from the compiled grammar directly.
 */
export interface GrammarAnalysis {
  /**
   * Keyed by method name ("Canonical" | "LALR" | "IELR").
   */
  perMethod: {
    [k: string]: MethodStatsInfo;
  };
  firstFollow: RuleFirstFollow[];
  /**
   * Keyed by rule name; each value is a self-contained SVG string.
   */
  railroad: {
    [k: string]: string;
  };
  verdict: ConflictVerdictInfo;
  symbolSet: SymbolSetInfo;
}
/**
 * One table-construction method's automaton size and conflict count.
 */
export interface MethodStatsInfo {
  states: number;
  conflicts: number;
}
/**
 * One nonterminal's FIRST/FOLLOW sets, each symbol classified via RenderedSymbol (EOF rendered as `$`).
 */
export interface RuleFirstFollow {
  name: string;
  first: RenderedSymbol[];
  follow: RenderedSymbol[];
}
/**
 * The same conflict classification `gramaire explain-conflict` prints as CLI prose, surfaced live: which of the four buckets the grammar's conflicts land in, the conflict count that survives with the grammar's own declared precedence applied, and — for a genuine conflict — each one rendered in grammar terms (empty otherwise).
 */
export interface ConflictVerdictInfo {
  verdict:
    "conflict-free" | "lalr-artifact" | "resolved-by-declaration" | "genuine";
  withPrecedenceConflicts: number;
  genuineConflicts: string[];
}
/**
 * The grammar's terminal alphabet, visible nonterminal set, and start symbol — the classic T = {...}, N = {...}, start-symbol summary a formal grammar reference states explicitly.
 */
export interface SymbolSetInfo {
  terminals: RenderedSymbol[];
  /**
   * Excludes a hoisted `( a | b )` group's synthetic __group_N rule, matching firstFollow's own visibleRules filter.
   */
  nonterminals: string[];
  start: string;
}
/**
 * Whether Ll.parseTraced accepts the target input, the DFA prediction cache's hit/miss counts (both overall and per rule), and every declaration-order-resolved ambiguity hit while walking it — from the same AtnSim.Cache(track = true) run that produced `parse`.
 */
export interface AtnDiagnostics {
  /**
   * Mirrors `parse.accepted` — both come from the same Ll.parseTraced run.
   */
  accepted: boolean;
  hits: number;
  misses: number;
  ambiguities: AmbiguityInfo[];
  /**
   * hits/misses folded down to rule names instead of collapsed into the two totals above — AtnSim.Cache.hitsByRule/missesByRule.
   */
  perRule: RuleAtnProfile[];
}
/**
 * One decision the ALL(*) predictor couldn't resolve down to a single alternative on its own — resolved by declaration order instead (first-alt-wins), the same notion AtnSim.Ambiguity carries.
 */
export interface AmbiguityInfo {
  rule: string;
  /**
   * The ATN's decision number for this block-start state.
   */
  decision: number;
  /**
   * The token position in the input where this decision was made.
   */
  pos: number;
  /**
   * The tied alternative indices, in first-alt-wins declaration order.
   */
  alts: number[];
}
/**
 * One rule's DFA prediction-cache hit/miss count, folded down from every decision belonging to it — AtnSim.Cache.hitsByRule/missesByRule.
 */
export interface RuleAtnProfile {
  rule: string;
  hits: number;
  misses: number;
}
/**
 * The ALL(*) engine's own internal rewrite of `productions` — the same two grammar transforms Ll.parse/Ll.parseTraced run before lowering to an ATN (precedence-climbing stratification, then direct-left-recursion elimination), rendered the same production-list way as `productions` instead of staying invisible. `afterPrecedence` equals `productions` when the grammar declares no `## Precedence`; `afterLeftRecursion` equals `afterPrecedence` when the grammar has no direct left recursion.
 */
export interface AllStarLowering {
  afterPrecedence: ProductionInfo[];
  afterLeftRecursion: ProductionInfo[];
}
/**
 * One ```gramaire fence's role and 1-based, inclusive line span in LabRequest.source's own raw text — the opening ```gramaire marker line through the closing ``` marker line.
 */
export interface FenceInfo {
  /**
   * 0-based, in document order.
   */
  index: number;
  /**
   * Lr.classifyFenceContent's "case is law" content-shape classification.
   */
  kind: "rule" | "tokens" | "settings" | "precedence";
  /**
   * The rule this fence defines — its first non-blank line's leading token — when `kind` is "rule"; null for every other kind.
   */
  nonterminal: string | null;
  startLine: number;
  endLine: number;
}

export const LAB_PROTOCOL_VERSION = 1;
