// The Lab's Web Worker — the mandatory boundary docs/playground-spec.md §5
// requires ("the Core stays FS-free... the same code runs unchanged in the
// worker"). Loads the Scala.js-linked engine and evaluates each LabRequest
// it's sent, replying with the matching LabResponse.
//
// The engine is loaded via a RUNTIME dynamic import of a static asset
// (public/lab/engine.mjs, generated by `npm run build:engine`, gitignored —
// never committed), NOT a normal `import ... from "./engine.mjs"`.
// Verified the hard way: a static import let Vite bundle the linked
// Scala.js output into this worker's own chunk, and Vite's minifier
// (esbuild) corrupted it in the process — the exact same request that
// evaluated correctly when the raw linked file was imported directly in
// Node failed with a bogus "lexical error in grammar source" once routed
// through the Vite-bundled chunk (built chunk was roughly half the size of
// the original, a dead giveaway of over-aggressive minification/DCE on
// code a general-purpose JS bundler wasn't designed to safely re-process).
// A dynamic import of a public/ URL is copied verbatim by Astro's build and
// never touches Vite's JS pipeline at all, so this can't recur.
//
// One request in flight is tracked by `id`, generated on the main thread:
// this worker itself does no debouncing or latest-wins dropping (that's a
// main-thread concern — see LabIsland.tsx) — it just answers whatever it's
// asked, tagged with the same id so a slow response for an old request
// can't be mistaken for the current one.
import type { LabRequest, LabResponse } from "./protocol";

export interface WorkerRequestMessage {
  id: number;
  request: LabRequest;
}

// The Evaluate tab's data (M5+): not part of LabProtocol (Scala never computes this — it only
// generates the JS source in LabResponse.evaluatorJs), so this is a hand-written type, not
// codegen'd from spec/lab-protocol-schema.json like the rest of this file's imports.
export interface AnnotatedBranch {
  rule: number;
  children: AnnotatedNode[];
  value: unknown;
}
export interface AnnotatedToken {
  token: string;
  text: string;
  value: unknown;
}
export type AnnotatedNode = AnnotatedBranch | AnnotatedToken;

export type EvaluationResult =
  { ok: true; tree: AnnotatedNode } | { ok: false; error: string };

export interface WorkerResponseMessage {
  id: number;
  response: LabResponse;
  evaluation: EvaluationResult | null;
}

type Engine = { gramaireLabEvaluate: (requestJson: string) => string };

const engineUrl = new URL(
  `${import.meta.env.BASE_URL}lab/engine.mjs`,
  self.location.href,
).href;
const enginePromise: Promise<Engine> = import(/* @vite-ignore */ engineUrl);

// Run the grammar author's own generated evaluator (LabResponse.evaluatorJs) against the accepted
// parse's CST. This executes arbitrary JS compiled from the grammar's `{% %}` actions — the same
// trust boundary `gramaire emit --backend js` already crosses when a user runs the downloaded file
// themselves: it's the author's own code, in their own tab, against their own input, with nothing
// server-side or cross-origin involved. A Blob URL (not a bare eval/Function) so it goes through
// the same ES-module import path as the engine itself, and gets revoked right after import so the
// browser can free the underlying text once the module's been instantiated.
async function runEvaluator(
  response: LabResponse,
): Promise<EvaluationResult | null> {
  const js = response.evaluatorJs;
  const cst = response.parse?.cst;
  if (!js || !cst) return null;
  const url = URL.createObjectURL(new Blob([js], { type: "text/javascript" }));
  try {
    const mod: { evaluateTraced: (cst: unknown) => AnnotatedNode } =
      await import(/* @vite-ignore */ url);
    return { ok: true, tree: mod.evaluateTraced(cst) };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  } finally {
    URL.revokeObjectURL(url);
  }
}

self.onmessage = async (event: MessageEvent<WorkerRequestMessage>) => {
  const { id, request } = event.data;
  const { gramaireLabEvaluate } = await enginePromise;
  const responseJson = gramaireLabEvaluate(JSON.stringify(request));
  const response: LabResponse = JSON.parse(responseJson);
  const evaluation = await runEvaluator(response);
  const message: WorkerResponseMessage = { id, response, evaluation };
  self.postMessage(message);
};
