// The Lab's Web Worker — the mandatory boundary docs/playground-spec.md §5
// requires ("the Core stays FS-free... the same code runs unchanged in the
// worker"). Loads the Scala.js-linked engine and evaluates each LabRequest
// it's sent, replying with the matching LabResponse.
//
// The engine is loaded via a RUNTIME dynamic import of a static asset
// (public/lab/engine.mjs, generated by `npm run build:engine`, gitignored —
// never committed), NOT a normal `import ... from "./engine.mjs"`.
// Verified the hard way: a static import let Vite bundle the linked
// Scala.js output into this worker's own chunk, and Vite's minifier
// (esbuild) corrupted it in the process — the exact same request that
// evaluated correctly when the raw linked file was imported directly in
// Node failed with a bogus "lexical error in grammar source" once routed
// through the Vite-bundled chunk (built chunk was roughly half the size of
// the original, a dead giveaway of over-aggressive minification/DCE on
// code a general-purpose JS bundler wasn't designed to safely re-process).
// A dynamic import of a public/ URL is copied verbatim by Astro's build and
// never touches Vite's JS pipeline at all, so this can't recur.
//
// One request in flight is tracked by `id`, generated on the main thread:
// this worker itself does no debouncing or latest-wins dropping (that's a
// main-thread concern — see LabIsland.tsx) — it just answers whatever it's
// asked, tagged with the same id so a slow response for an old request
// can't be mistaken for the current one.
import type { LabRequest, LabResponse } from "./protocol";

export interface WorkerRequestMessage {
  id: number;
  request: LabRequest;
}

export interface WorkerResponseMessage {
  id: number;
  response: LabResponse;
}

type Engine = { gramarkLabEvaluate: (requestJson: string) => string };

const engineUrl = new URL(
  `${import.meta.env.BASE_URL}lab/engine.mjs`,
  self.location.href,
).href;
const enginePromise: Promise<Engine> = import(/* @vite-ignore */ engineUrl);

self.onmessage = async (event: MessageEvent<WorkerRequestMessage>) => {
  const { id, request } = event.data;
  const { gramarkLabEvaluate } = await enginePromise;
  const responseJson = gramarkLabEvaluate(JSON.stringify(request));
  const response: LabResponse = JSON.parse(responseJson);
  const message: WorkerResponseMessage = { id, response };
  self.postMessage(message);
};
