-- | A backend that emits a JavaScript **evaluator interface** for the structure-
-- | only action-binding model (the consensus of the action-binding review). The
-- | grammar carries no host code: alternatives are named with `# Label` (D26)
-- | and their children with `name:` fields (D28). This backend bakes the
-- | per-production metadata into a small ES module that folds a `gramaire-cst`
-- | JSON tree bottom-up against a caller-supplied **handler object** — one
-- | function per label, receiving its children by field name and positionally.
-- |
-- | The same grammar thus evaluates in any host: the Lab supplies a JavaScript
-- | handler object, the test suite a PureScript record (`Gramaire.Transform`).
-- | This is the `Actions "js"` capability — a typed AST/evaluator for the `js`
-- | profile — without a line of host code in the `.gram.md`.
module Gramaire.Backend.Js
  ( backend
  , emit
  ) where

import Prelude

import Data.Array as Array
import Data.Maybe (Maybe(..))
import Data.String (joinWith)
import Data.String.CodeUnits (singleton, toCharArray)
import Gramaire.Backend (Backend, Capability(..), allStrategies)
import Gramaire.IR (IR, IRRef(..), IRRule)

-- | The JS backend: one `<Name>.js` ES module exposing `labels`, `fold`, and
-- | `evaluate`.
backend :: Backend
backend =
  { name: "js"
  , capabilities: [ Actions "js" ]
  , strategies: allStrategies
  , emit: \ir -> [ { path: ir.grammar.name <> ".js", contents: emit ir } ]
  }

-- | Render the evaluator module: the baked per-production metadata, the public
-- | label→fields shape, and the fixed folding runtime.
emit :: IR -> String
emit ir =
  joinWith "\n"
    [ "// Generated by gramaire --backend js for grammar " <> jsStr ir.grammar.name <> "."
    , "// Structure-only evaluator: bind one handler per label; each receives"
    , "// ({ named, pos }) — children by field name and positionally — and returns a value."
    , "// `node` is a gramaire-cst JSON tree ({ rule, children } | { token, text })."
    , ""
    , "// production id -> { label, fields }"
    , "const meta = [" <> joinWith ", " (map metaEntry ir.grammar.rules) <> "];"
    , ""
    , "// label -> field names a handler can read (the handler shape)"
    , "export const labels = {" <> joinWith ", " labelEntries <> "};"
    , ""
    , runtime
    ]
  where
  metaEntry :: IRRule -> String
  metaEntry r =
    "{ label: " <> maybeStr r.label <> ", fields: [" <> joinWith ", " (map (maybeStr <<< refField) r.rhs) <> "] }"

  labelEntries =
    Array.mapMaybe labelEntry ir.grammar.rules

  labelEntry r = case r.label of
    Just lbl -> Just (jsStr lbl <> ": [" <> joinWith ", " (map jsStr (Array.mapMaybe refField r.rhs)) <> "]")
    Nothing -> Nothing

refField :: IRRef -> Maybe String
refField = case _ of
  IRRefNT _ f -> f
  IRRefT _ f -> f

maybeStr :: Maybe String -> String
maybeStr = case _ of
  Just s -> jsStr s
  Nothing -> "null"

-- The fixed runtime: bottom-up fold with field-named children and a passthrough
-- default (an unlabelled or unhandled node with a single value child passes it
-- through). Token children are exposed as `{ terminal, text }`.
runtime :: String
runtime =
  joinWith "\n"
    [ "function unwrap(c) { return 'val' in c ? c.val : c.tok; }"
    , ""
    , "function fold(node, handlers, fallback) {"
    , "  if (node.token !== undefined) return { tok: { terminal: node.token, text: node.text } };"
    , "  const m = meta[node.rule] || { label: null, fields: [] };"
    , "  const kids = node.children.map((k) => fold(k, handlers, fallback));"
    , "  const h = m.label != null ? handlers[m.label] : undefined;"
    , "  if (h) {"
    , "    const named = {};"
    , "    m.fields.forEach((f, i) => { if (f != null && kids[i] !== undefined) named[f] = unwrap(kids[i]); });"
    , "    return { val: h({ named, pos: kids.map(unwrap) }) };"
    , "  }"
    , "  return { val: fallback(kids) };"
    , "}"
    , ""
    , "function defaultFallback(kids) {"
    , "  const vals = kids.filter((c) => 'val' in c);"
    , "  if (vals.length === 1) return vals[0].val;"
    , "  return kids.map(unwrap);"
    , "}"
    , ""
    , "// Fold a gramaire-cst tree against `handlers` (label -> ({named,pos}) => value)."
    , "export function evaluate(node, handlers, fallback = defaultFallback) {"
    , "  return unwrap(fold(node, handlers, fallback));"
    , "}"
    ]

-- A JS string literal (double-quoted), escaping the characters that matter.
jsStr :: String -> String
jsStr s = "\"" <> joinWith "" (map esc (toCharArray s)) <> "\""
  where
  esc c = case c of
    '"' -> "\\\""
    '\\' -> "\\\\"
    '\n' -> "\\n"
    _ -> singleton c
