-- | A `recognizer` + `cst` codegen backend: `gramaire-ir` in, a TypeScript
-- | parser out.
-- |
-- | This is the second real backend after `ebnf`, and the first *codegen* one —
-- | it emits runnable source, not a static artifact. It reads only the IR (the
-- | serialized parse tables and the grammar slice) and produces a self-contained
-- | ES module: the LR(1) shift/reduce driver (a direct port of
-- | `Gramaire.Parser.run`) over the emitted `ACTION` / `GOTO` / `PRODS` tables,
-- | building the generic CST of `spec/cst-schema.json` — a `branch` per
-- | reduction and a `token` leaf per shift. No lexer is emitted: `parse` takes a
-- | pre-lexed `Token[]`, since tokenization is per-language (the conformance
-- | harness supplies the input lexers).
-- |
-- | On top of the CST it emits the typed **Visitor** of [D24]: an interface with
-- | one method per production (named by its `# Label` when present, else by rule
-- | id) plus `token`, and a `fold` catamorphism that walks the tree bottom-up.
-- | Two files are produced: `<Name>.ts` (implementation) and `<Name>.d.ts` (the
-- | public type surface for consumers of the compiled JS).
module Gramaire.Backend.Ts
  ( backend
  , emit
  , emitDts
  ) where

import Prelude

import Data.Array as Array
import Data.Map (Map)
import Data.Map as Map
import Data.Maybe (fromMaybe)
import Data.Set as Set
import Data.String (joinWith)
import Data.Tuple (Tuple(..))
import Gramaire.Backend (Backend, Capability(..))
import Gramaire.IR (IR, IRAct(..), IROn(..), IRTerminal(..))
import Gramaire.Json (Json(JString))
import Gramaire.Json as Json

-- | The TypeScript backend: a `recognizer` + `cst` codegen backend emitting a
-- | `.ts` implementation and a `.d.ts` declaration file named after the grammar.
backend :: Backend
backend =
  { name: "ts"
  , capabilities: [ Recognizer, Cst ]
  , strategies: [ "lr" ]
  , emit: \ir ->
      [ { path: ir.grammar.name <> ".ts", contents: emit ir }
      , { path: ir.grammar.name <> ".d.ts", contents: emitDts ir }
      ]
  }

-- | Emit the `<Name>.ts` implementation module.
emit :: IR -> String
emit ir =
  joinWith "\n"
    [ banner ir "TypeScript recognizer + CST"
    , ""
    , cstTypes
    , ""
    , actionConst ir
    , gotoConst ir
    , prodsConst ir
    , ""
    , parseFn
    , ""
    , errorClass
    , ""
    , visitorInterface ir
    , ""
    , foldFn ir
    ]

-- | Emit the `<Name>.d.ts` public type surface.
emitDts :: IR -> String
emitDts ir =
  joinWith "\n"
    [ banner ir "TypeScript declarations"
    , ""
    , cstTypes
    , ""
    , "export declare function parse(tokens: Token[]): CstNode;"
    , ""
    , "export declare class ParseError extends Error {}"
    , ""
    , visitorInterface ir
    , ""
    , "export declare function fold<T>(node: CstNode, v: Visitor<T>): T;"
    ]

banner :: IR -> String -> String
banner ir what =
  joinWith "\n"
    [ "// GENERATED by Gramaire from the `" <> ir.grammar.name <> "` grammar — " <> what <> "."
    , "// Do not edit; regenerate with `gramaire emit --backend ts`."
    ]

-- The CST node vocabulary, shared by the `.ts` and `.d.ts` (matches
-- spec/cst-schema.json: a branch tagged with its rule id, a token leaf).
cstTypes :: String
cstTypes =
  joinWith "\n"
    [ "export type Token = { terminal: string; text: string };"
    , "export type CstToken = { token: string; text: string };"
    , "export type CstBranch = { rule: number; children: CstNode[] };"
    , "export type CstNode = CstBranch | CstToken;"
    ]

-- ACTION[state][terminalName] -> action; the empty-string key is end-of-input.
actionConst :: IR -> String
actionConst ir =
  "const ACTION: Record<number, Record<string, Act>> = {\n"
    <> joinWith "\n" (map row ir.tables.action)
    <> "\n};\n"
  where
  names = terminalNames ir
  row r =
    "  " <> show r.state <> ": { "
      <> joinWith ", " (map entry r.entries)
      <> " },"
  entry e = key (onName names e.on) <> ": " <> act e.action
  act = case _ of
    ActShift n -> "{ shift: " <> show n <> " }"
    ActReduce n -> "{ reduce: " <> show n <> " }"
    ActAccept -> "{ accept: true }"

-- GOTO[state][nonterminalId] -> state.
gotoConst :: IR -> String
gotoConst ir =
  "\nconst GOTO: Record<number, Record<number, number>> = {\n"
    <> joinWith "\n" (map row ir.tables.goto)
    <> "\n};\n"
  where
  row r =
    "  " <> show r.state <> ": { "
      <> joinWith ", " (map (\e -> show e.nonterminal <> ": " <> show e.to) r.entries)
      <> " },"

-- PRODS[ruleId] -> { lhs nonterminal id, rhs length }, in rule-id order.
prodsConst :: IR -> String
prodsConst ir =
  "\nconst PRODS: { lhs: number; len: number }[] = [\n"
    <> joinWith "\n" (map prod (Array.sortWith _.id ir.grammar.rules))
    <> "\n];"
  where
  prod r = "  { lhs: " <> show r.lhs <> ", len: " <> show (Array.length r.rhs) <> " }, // " <> show r.id

parseFn :: String
parseFn =
  joinWith "\n"
    [ "type Act = { shift: number } | { reduce: number } | { accept: true };"
    , ""
    , "// The generic LR(1) shift/reduce driver, building the CST."
    , "export function parse(tokens: Token[]): CstNode {"
    , "  const states: number[] = [0];"
    , "  const values: CstNode[] = [];"
    , "  let pos = 0;"
    , "  for (;;) {"
    , "    const state = states[states.length - 1]!;"
    , "    const tok = tokens[pos];"
    , "    const look = tok ? tok.terminal : \"\"; // \"\" is end-of-input"
    , "    const act = ACTION[state]?.[look];"
    , "    if (!act) {"
    , "      throw new ParseError("
    , "        tok"
    , "          ? `unexpected token ${look} in state ${state}`"
    , "          : `unexpected end of input in state ${state}`,"
    , "      );"
    , "    }"
    , "    if (\"shift\" in act) {"
    , "      states.push(act.shift);"
    , "      values.push({ token: tok!.terminal, text: tok!.text });"
    , "      pos++;"
    , "    } else if (\"reduce\" in act) {"
    , "      const p = PRODS[act.reduce]!;"
    , "      const kids = p.len === 0 ? [] : values.splice(values.length - p.len, p.len);"
    , "      states.splice(states.length - p.len, p.len);"
    , "      const under = states[states.length - 1]!;"
    , "      const g = GOTO[under]?.[p.lhs];"
    , "      if (g === undefined) throw new ParseError(\"missing goto after reduce\");"
    , "      states.push(g);"
    , "      values.push({ rule: act.reduce, children: kids });"
    , "    } else {"
    , "      return values[values.length - 1]!;"
    , "    }"
    , "  }"
    , "}"
    ]

errorClass :: String
errorClass = "export class ParseError extends Error {}"

-- The typed Visitor (D24): a method per production + `token`.
visitorInterface :: IR -> String
visitorInterface ir =
  "export interface Visitor<T> {\n"
    <> "  token(node: CstToken): T;\n"
    <> joinWith "\n" (map method (Array.sortWith _.id ir.grammar.rules))
    <> "\n}"
  where
  names = methodNames ir
  method r = "  " <> name r <> "(children: T[]): T;"
  name r = fromMaybe ("rule" <> show r.id) (Map.lookup r.id names)

-- The catamorphism: fold children bottom-up, dispatch on rule id to its method.
foldFn :: IR -> String
foldFn ir =
  joinWith "\n"
    [ "export function fold<T>(node: CstNode, v: Visitor<T>): T {"
    , "  if (\"token\" in node) return v.token(node);"
    , "  const kids = node.children.map((c) => fold(c, v));"
    , "  switch (node.rule) {"
    , joinWith "\n" (map arm (Array.sortWith _.id ir.grammar.rules))
    , "    default:"
    , "      throw new Error(`unknown rule ${node.rule}`);"
    , "  }"
    , "}"
    ]
  where
  names = methodNames ir
  arm r = "    case " <> show r.id <> ": return v." <> name r <> "(kids);"
  name r = fromMaybe ("rule" <> show r.id) (Map.lookup r.id names)

-- Method name per rule: its `# Label` when present and unique, else `rule<id>`
-- (always unique), so the interface never has a duplicate member.
methodNames :: IR -> Map Int String
methodNames ir = (Array.foldl step { used: Set.empty, out: Map.empty } (Array.sortWith _.id ir.grammar.rules)).out
  where
  step acc r =
    let
      preferred = fromMaybe fallback r.label
      fallback = "rule" <> show r.id
      name = if Set.member preferred acc.used then fallback else preferred
    in
      { used: Set.insert name acc.used, out: Map.insert r.id name acc.out }

-- A terminal's lexer name: a literal's spelling, a class's name — exactly the
-- `terminal` field the input tokens carry.
terminalNames :: IR -> Map Int String
terminalNames ir = Map.fromFoldable (map entry ir.grammar.terminals)
  where
  entry = case _ of
    IRLiteral i spelling -> Tuple i spelling
    IRClass i name -> Tuple i name

onName :: Map Int String -> IROn -> String
onName names = case _ of
  OnTerm i -> fromMaybe ("t?" <> show i) (Map.lookup i names)
  OnEof -> ""

-- A TS/JSON object key as a quoted string literal (canonical escaping).
key :: String -> String
key s = Json.stringify (JString s)
