import { signal } from "@preact/signals";
import type { Signal } from "@preact/signals";
import type { LabRequest, LabResponse, Strategy } from "../protocol";
import { LAB_PROTOCOL_VERSION } from "../protocol";
import type {
  EvaluationResult,
  WorkerRequestMessage,
  WorkerResponseMessage,
} from "../worker";
import { internalErrorResponse } from "../internalDiagnosticResponse";

const DEBOUNCE_MS = 200;

export interface LabWorkerHandle {
  response: Signal<LabResponse | null>;
  /** The exact `source` text `response` was computed for. `onmessage`'s `id !== latestSentId`
   * check only guards against an OLDER request's response arriving after a NEWER one has already
   * been SENT — it says nothing about whether the document has since moved past the text a
   * still-in-flight (not yet superseded) request was dispatched for. Two edits within the same
   * debounce window (the second committed — and its own text change applied to `blocks` — before
   * the first request's response comes back) would otherwise apply fence layout describing the
   * FIRST edit's text against the SECOND edit's already-current content. A consumer rebuilding
   * document structure from `response.fences` must first check `responseSource.value` against its
   * own current serialized text and skip the rebuild on a mismatch (the next, matching response
   * will always follow once things settle — see GrimoireNotebookIsland.tsx's own effect). */
  responseSource: Signal<string | null>;
  pending: Signal<boolean>;
  /** The grammar's own `{% %}` actions, run by the worker over the accepted parse
   * (`LabResponse.evaluatorJs`, generated by `BackendJs.emitTraced`) — `tree.value` is the root's
   * computed value (e.g. the numeric result of a calculator grammar). Null when the grammar has
   * no actions/evaluator, when the parse was rejected, or before the first response. */
  evaluation: Signal<EvaluationResult | null>;
  /** Debounced, latest-wins: a fast follow-up call supersedes an in-flight one, matching
   * LabIsland.tsx's own scheduleEvaluate convention. */
  evaluate: (source: string, input: string, strategy: Strategy) => void;
  dispose: () => void;
}

/**
 * A standalone Web Worker + debounce/latest-wins lifecycle around `LabApi.evaluate`, independent
 * of LabIsland.tsx's own module-level copy of the same pattern — the Grimoire Notebook is a
 * separate page with its own state, not a mode bolted onto the existing Lab (see
 * docs/rebrand-gramaire-plan.md's "status of the notebook feature" note). Always builds with
 * `method: "Canonical"` — the notebook has no method picker in this first cut, matching
 * LabIsland's own doc comment that `forest`/`analysis` never depend on it anyway.
 */
export function createLabWorker(): LabWorkerHandle {
  const response = signal<LabResponse | null>(null);
  const responseSource = signal<string | null>(null);
  const pending = signal(false);
  const evaluation = signal<EvaluationResult | null>(null);

  let worker: Worker | null = null;
  let requestId = 0;
  let latestSentId = 0;
  // The `source` of the request currently tracked by `latestSentId` — captured at SEND time
  // (inside the same debounce callback that assigns `latestSentId`), so it always names exactly
  // the text `response.value` describes once that request's answer is accepted below.
  let sourceInFlight = "";
  let debounceTimer: ReturnType<typeof setTimeout> | undefined;
  let pendingRequest: LabRequest | null = null;

  function ensureWorker(): Worker {
    if (worker) return worker;
    worker = new Worker(new URL("../worker.ts", import.meta.url), {
      type: "module",
    });
    worker.onmessage = (event: MessageEvent<WorkerResponseMessage>) => {
      const { id, response: resp, evaluation: evalResult } = event.data;
      if (id !== latestSentId) return; // stale — a newer request has already been sent
      response.value = resp;
      responseSource.value = sourceInFlight;
      evaluation.value = evalResult;
      pending.value = false;
    };
    worker.onerror = (event) => {
      pending.value = false;
      response.value = internalErrorResponse(
        LAB_PROTOCOL_VERSION,
        `Grimoire Notebook worker failed to start (${event.message}) — reload the page.`,
      );
      responseSource.value = sourceInFlight;
    };
    return worker;
  }

  function evaluate(source: string, input: string, strategy: Strategy) {
    pendingRequest = { source, input, method: "Canonical", strategy };
    pending.value = true;
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      if (!pendingRequest) return;
      const id = ++requestId;
      latestSentId = id;
      sourceInFlight = pendingRequest.source;
      const message: WorkerRequestMessage = { id, request: pendingRequest };
      ensureWorker().postMessage(message);
    }, DEBOUNCE_MS);
  }

  function dispose() {
    clearTimeout(debounceTimer);
    worker?.terminate();
    worker = null;
  }

  return { response, responseSource, pending, evaluation, evaluate, dispose };
}
