package gramark

// A `recognizer`-only, `ll-star`-only codegen backend: `gramark-ir` in, a self-contained
// TypeScript ATN-driven recognizer out — `IR.atn`'s first *executable* consumer (every other
// reader, `BackendDot`'s `--strategy ll-star` rendering, only ever displays it).
//
// **v1 scope, deliberately recognizer-only** (`Capability.Recognizer`, not `Capability.Cst`):
// reproducing `Ll.parse`'s exact Cst (matching production ids, folding the left-recursion/
// precedence-cascade rewrites back onto the original grammar) needs IR-level provenance for
// `LeftRec.Fold`/`PrecClimb.Tag` that does not exist yet — `IR.withStrategy` serializes only the
// already-rewritten `atn`, discarding the fold information `Ll.parse` itself needs for the same
// job. Shipping recognizer-only first and CST second mirrors this port's own Phase 1 -> Phase 2
// staging for the Scala engine itself, not a scope cut invented for this backend alone.
//
// The emitted module is a straight, SLL-only transliteration of `AtnSim.closure`/`move`/`predict`
// and `Ll.recognize`'s own `parseRule`/`walk` drive loop (`predict.scala`'s two-stage SLL-then-
// full-LL retry, its DFA cache, and its ambiguity reporting are NOT ported for v1 — a plain,
// uncached SLL walk is enough to prove `IR.atn` is a real, executable substrate; the full-LL
// fallback and diagnostics are follow-up work, same as the engine's own already-documented
// scope boundary in `AtnSim.scala`/`docs/all-star-port-plan.md` §6). No *runtime* left-recursion
// handling is needed either: the ATN this reads is already the `LeftRec`-eliminated one `IR.atn`
// serializes server-side, so the emitted TS never sees a left-recursive shape to rewrite.
object BackendAtnTs:
  val backend: Backend = Backend(
    name = "atn-ts",
    capabilities = Vector(Capability.Recognizer),
    strategies = Vector("ll-star"),
    emit = ir => Vector(Output(s"${ir.grammar.name}.atn.ts", emit(ir)))
  )

  private def banner(ir: IR, what: String): String =
    s"// GENERATED by Gramark from the `${ir.grammar.name}` grammar — $what.\n" +
      "// Do not edit; regenerate with `gramark emit --backend atn-ts --strategy ll-star`."

  // A TS/JSON object key or string literal (canonical escaping).
  private def str(s: String): String = Json.stringify(Json.JString(s))

  private def transJson(t: IRAtnTrans): String = t match
    case IRAtnTrans.IRAtnEps(target) =>
      s"""{ kind: "eps", target: $target }"""
    case IRAtnTrans.IRAtnAtom(label, target) =>
      s"""{ kind: "atom", label: ${str(label)}, target: $target }"""
    case IRAtnTrans.IRAtnRule(name, target, follow) =>
      s"""{ kind: "rule", name: ${str(name)}, target: $target, follow: $follow }"""

  private def stateJson(s: IRAtnState): String =
    val decision = s.decision.fold("null")(_.toString)
    val transitions = s.transitions.map(transJson).mkString(", ")
    s"""  { id: ${s.id}, rule: ${str(s.rule)}, kind: ${str(
        s.kind
      )}, decision: $decision, transitions: [$transitions] },"""

  // `IR.atn`'s states, dense by id — indexing directly into this array is `Atn.stateAt`'s own
  // "id is the index" contract, so the runtime below never needs a lookup map.
  private def statesConst(atn: IRAtn): String =
    "const STATES: AtnState[] = [\n" + atn.states
      .sortBy(_.id)
      .map(stateJson)
      .mkString("\n") + "\n];"

  private val types: String =
    Vector(
      "type TransKind = \"eps\" | \"atom\" | \"rule\";",
      "type Trans =",
      "  | { kind: \"eps\"; target: number }",
      "  | { kind: \"atom\"; label: string; target: number }",
      "  | { kind: \"rule\"; name: string; target: number; follow: number };",
      "type StateKind = \"ruleStart\" | \"ruleStop\" | \"basic\" | \"blockStart\" | \"blockEnd\";",
      "type AtnState = {",
      "  id: number;",
      "  rule: string;",
      "  kind: StateKind;",
      "  decision: number | null;",
      "  transitions: Trans[];",
      "};",
      "export type Token = { terminal: string; text: string };"
    ).mkString("\n")

  // A straight port of `AtnSim.Config` (`core/src/main/scala/gramark/AtnSim.scala`): an ATN state,
  // the alternative it explores, and the `RuleCall` return stack (innermost first).
  private val configType: String = "type Config = { state: number; alt: number; stack: number[] };"

  // Mirrors `AtnSim.scala`'s own `maxDepth` exactly — a closure recursing through this many nested
  // `RuleCall`s without consuming input is treated as non-terminating (left recursion) and pruned.
  private val maxDepthConst: String = "const MAX_DEPTH = 80;"

  // `AtnSim.closure`/`move`/`uniqueAlt`/`completed`/`resolve`/`predict` (SLL only — see the module
  // header) and `Ll.recognize`'s `parseRule`/`walk` drive loop, transliterated line-for-line.
  private val runtime: String =
    Vector(
      "function stateAt(id: number): AtnState {",
      "  return STATES[id]!;",
      "}",
      "",
      "// The ε-closure of one configuration: every configuration reachable without consuming",
      "// input that sits at a terminal edge (an atom) or has returned to an empty call stack.",
      "function closure(c0: Config, seedLen: number): Config[] {",
      "  const seen = new Set<string>();",
      "  const out: Config[] = [];",
      "  function key(c: Config): string {",
      "    return c.state + \"|\" + c.stack.join(\",\");",
      "  }",
      "  function go(c: Config): void {",
      "    if (c.stack.length - seedLen > MAX_DEPTH) return;",
      "    const k = key(c);",
      "    if (seen.has(k)) return;",
      "    seen.add(k);",
      "    const st = stateAt(c.state);",
      "    if (st.transitions.length === 1 && st.transitions[0]!.kind === \"atom\") {",
      "      out.push(c);",
      "      return;",
      "    }",
      "    if (st.transitions.length === 0) {",
      "      if (c.stack.length === 0) {",
      "        out.push(c);",
      "      } else {",
      "        const [ret, ...tail] = c.stack;",
      "        go({ state: ret!, alt: c.alt, stack: tail });",
      "      }",
      "      return;",
      "    }",
      "    for (const t of st.transitions) {",
      "      if (t.kind === \"eps\") go({ state: t.target, alt: c.alt, stack: c.stack });",
      "      else if (t.kind === \"rule\")",
      "        go({ state: t.target, alt: c.alt, stack: [t.follow, ...c.stack] });",
      "      // a lone \"atom\" transition is handled by the length-1 case above; a state never",
      "      // mixes an atom edge with any other edge (Atn's own invariant).",
      "    }",
      "  }",
      "  go(c0);",
      "  return out;",
      "}",
      "",
      "function closureAll(configs: Config[], seedLen: number): Config[] {",
      "  const seen = new Set<string>();",
      "  const out: Config[] = [];",
      "  for (const c of configs) {",
      "    for (const c2 of closure(c, seedLen)) {",
      "      const k = c2.state + \"#\" + c2.alt + \"#\" + c2.stack.join(\",\");",
      "      if (!seen.has(k)) {",
      "        seen.add(k);",
      "        out.push(c2);",
      "      }",
      "    }",
      "  }",
      "  return out;",
      "}",
      "",
      "// Advance a lookahead-leaf configuration over one input terminal; a configuration with no",
      "// matching edge dies.",
      "function move(term: string, c: Config): Config[] {",
      "  const st = stateAt(c.state);",
      "  const t = st.transitions[0];",
      "  if (st.transitions.length === 1 && t !== undefined && t.kind === \"atom\" && t.label === term)",
      "    return [{ ...c, state: t.target }];",
      "  return [];",
      "}",
      "",
      "// The lowest (earliest-declared) alt among `configs` — first-alternative-wins on a genuine",
      "// tie, ALL(*)'s disambiguation convention.",
      "function uniqueAlt(configs: Config[]): number | null {",
      "  if (configs.length === 0) return null;",
      "  const first = configs[0]!.alt;",
      "  let min = first;",
      "  for (const c of configs) if (c.alt < min) min = c.alt;",
      "  return configs.every((c) => c.alt === min) ? min : null;",
      "}",
      "",
      "// A configuration whose rule has run to its end with an empty call stack.",
      "function completed(c: Config): boolean {",
      "  return stateAt(c.state).transitions.length === 0 && c.stack.length === 0;",
      "}",
      "",
      "// Prefer a completed configuration over one merely pending on more input; first-alt-wins",
      "// among whatever's left. `null` only when `configs` itself is empty.",
      "function resolve(configs: Config[]): number | null {",
      "  const completedConfigs = configs.filter(completed);",
      "  const candidates = completedConfigs.length > 0 ? completedConfigs : configs;",
      "  if (candidates.length === 0) return null;",
      "  let min = candidates[0]!.alt;",
      "  for (const c of candidates) if (c.alt < min) min = c.alt;",
      "  return min;",
      "}",
      "",
      "// Predict the alternative to take at `decision` (a blockStart) for the input from `pos0` —",
      "// SLL only (seed always []), no DFA cache, no full-LL retry: see the module header for why.",
      "function predict(decision: number, input: Token[], pos0: number): number | null {",
      "  const st = stateAt(decision);",
      "  const starts: Config[] = st.transitions.map((t, i) =>",
      "    t.kind === \"eps\"",
      "      ? { state: t.target, alt: i, stack: [] }",
      "      : { state: decision, alt: i, stack: [] },",
      "  );",
      "  let configs = closureAll(starts, 0);",
      "  let pos = pos0;",
      "  for (;;) {",
      "    const u = uniqueAlt(configs);",
      "    if (u !== null) return u;",
      "    const tok = input[pos];",
      "    if (tok === undefined) return resolve(configs);",
      "    const moved = configs.flatMap((c) => move(tok.terminal, c));",
      "    const advanced = closureAll(moved, 0);",
      "    if (advanced.length === 0) return resolve(configs);",
      "    configs = advanced;",
      "    pos += 1;",
      "  }",
      "}",
      "",
      "// Parse the rule whose RuleStart is `ruleStart`, from `pos`; return the position after it,",
      "// or null if the input does not match the predicted alternative.",
      "function parseRule(ruleStart: number, input: Token[], pos: number): number | null {",
      "  const st = stateAt(ruleStart);",
      "  const only = st.transitions[0];",
      "  if (st.transitions.length !== 1 || only === undefined || only.kind !== \"eps\") return null;",
      "  const blockStart = only.target;",
      "  const i = predict(blockStart, input, pos);",
      "  if (i === null) return null;",
      "  const alt = stateAt(blockStart).transitions[i];",
      "  if (alt === undefined || alt.kind !== \"eps\") return null;",
      "  return walk(alt.target, input, pos);",
      "}",
      "",
      "// Follow one alternative's transition chain, consuming input, until its block end.",
      "function walk(state: number, input: Token[], pos: number): number | null {",
      "  const st = stateAt(state);",
      "  if (st.kind === \"blockEnd\") return pos;",
      "  const only = st.transitions[0];",
      "  if (st.transitions.length !== 1 || only === undefined) return null;",
      "  if (only.kind === \"atom\") {",
      "    const tok = input[pos];",
      "    if (tok !== undefined && tok.terminal === only.label) return walk(only.target, input, pos + 1);",
      "    return null;",
      "  }",
      "  if (only.kind === \"rule\") {",
      "    const result = parseRule(only.target, input, pos);",
      "    if (result === null) return null;",
      "    return walk(only.follow, input, result);",
      "  }",
      "  return walk(only.target, input, pos);",
      "}",
      "",
      "// Accept `input` iff the grammar's start rule recognizes the whole stream.",
      "export function recognize(input: Token[]): boolean {",
      "  const result = parseRule(START, input, 0);",
      "  return result !== null && result === input.length;",
      "}"
    ).mkString("\n")

  /** Emit the `<Name>.atn.ts` module, or an error-commented stub if `ir.atn` is absent (shouldn't
    * happen via `gramark emit`, which gates on `--strategy ll-star` before calling any backend —
    * defensive for a caller that constructs/invokes this backend directly).
    */
  def emit(ir: IR): String = ir.atn match
    case None =>
      banner(ir, "ATN recognizer") +
        "\n// ERROR: no atn on this IR — build with --strategy ll-star.\n" +
        "export function recognize(_input: { terminal: string; text: string }[]): boolean {\n" +
        "  throw new Error(\"no ATN available\");\n" +
        "}\n"
    case Some(atn) =>
      Vector(
        banner(ir, "ATN recognizer (strategy ll-star)"),
        "",
        types,
        "",
        configType,
        maxDepthConst,
        "",
        s"const START = ${atn.start};",
        statesConst(atn),
        "",
        runtime
      ).mkString("\n")
