package gramark

// A `Cst`-capable, `fastparse`-targeting codegen backend — the opt-in, production-grade-
// performance counterpart to the dependency-free `scala-peg` backend (`BackendScalaPeg`),
// reading the SAME `IR.rewritten` section (see `IR.rewrittenGrammarOf`'s own doc).
//
// **Why this isn't just `BackendScalaPeg` with `fastparse` combinators swapped in for the
// hand-rolled `Option`-based backtracking**: `fastparse`'s `ParserInput` is hardcoded to
// `Char`/`String` — there is no generic or token-stream `ParserInput` (verified against
// `fastparse`'s own source: `IndexedParserInput`/`IteratorParserInput` both fix the element type
// to `Char`, and there is no documented extension point for a custom element type). It therefore
// cannot consume the same already-lexed `Vector[Token]` `Ll.parse`/`BackendScalaPeg`'s generated
// code reads directly.
//
// The alternative — emitting a SECOND, `fastparse`-native lexer (translating `IR.lexer`'s token
// classes/regexes into `fastparse` char-combinators) so this backend could parse raw source text
// in one pass — was deliberately rejected: it would need its own conformance proof that the
// emitted lexer reproduces Gramark's real `Scanner` token stream byte-for-byte, the same bar
// `docs/multi-backend-implementation-plan.md`'s D31 already holds any alternate lexer to, and
// would make this backend a fundamentally different (and much larger) undertaking than "reuse
// `IR.rewritten`, target a different combinator style" — the scope the PEG-engine plan commits to.
//
// Instead, this backend keeps the SAME "already-lexed tokens in" contract as `BackendScalaPeg`:
// each already-lexed `Token`'s TERMINAL is mapped to one synthetic `Char` (Unicode Private Use
// Area, `` + a per-distinct-terminal index, built fresh per `parse` call from the actual
// tokens), producing a synthetic `String` of the same length as the token vector for `fastparse`'s
// ordinary `CharPred` combinators to match against, one terminal-check at a time; `fastparse`'s own
// `Index` primitive recovers which real `Token` a matched synthetic char corresponds to, so a
// built `Cst.Token` always carries the REAL terminal/text, never the synthetic stand-in. This is a
// real, idiomatic `fastparse` parser — genuinely compiled and run by the parity gate — just driven
// by a synthetic input `fastparse` can actually consume instead of the token vector directly.
object BackendScalaPegFastparse:
  val backend: Backend = Backend(
    name = "scala-peg-fastparse",
    capabilities = Vector(Capability.Cst),
    strategies = Vector("ll-star"),
    emit = ir => Vector(Output(s"${ir.grammar.name}Fastparse.scala", emit(ir)))
  )

  private def banner(ir: IR, what: String): String =
    s"// GENERATED by Gramark from the `${ir.grammar.name}` grammar — $what.\n" +
      "// Do not edit; regenerate with `gramark emit --backend scala-peg-fastparse --strategy ll-star`."

  private[gramark] def strLit(s: String): String =
    "\"" + s.flatMap {
      case '"'  => "\\\""
      case '\\' => "\\\\"
      case '\n' => "\\n"
      case '\t' => "\\t"
      case '\r' => "\\r"
      case c    => c.toString
    } + "\""

  private def ident(name: String): String =
    val safe = name.map(c => if c.isLetterOrDigit || c == '_' then c else '_')
    if safe.headOption.exists(_.isDigit) then s"_$safe" else safe

  private def parseFnName(rule: String): String = s"parse_${ident(rule)}"

  // See `BackendScalaPeg.safeObjName`'s own doc — same reserved-word collision, same fix (only
  // backtick-quote on an actual collision, so every non-keyword grammar name's goldens stay
  // byte-unchanged).
  private[gramark] def safeObjName(name: String): String =
    val id = ident(name)
    if BackendScalaPeg.scalaKeywords.contains(id) then s"`$id`" else id

  private def originExpr(origin: IRAltOrigin, kidsExpr: String): String = origin match
    case IRAltOrigin.Unwrap           => s"$kidsExpr.head"
    case IRAltOrigin.Original(prodId) => s"Cst.Branch($prodId, $kidsExpr)"

  // Identical to `BackendScalaPeg`'s own `tagExpr` — `IRProv` resolution doesn't depend on which
  // combinator library drives the match, only on the (already fully-parsed) `kids`/`acc` values.
  private def tagExpr(prov: IRProv, kidsVar: String, accVar: Option[String], depth: Int): String =
    prov match
      case IRProv.Leaf(origin) => originExpr(origin, kidsVar)
      case IRProv.OpLeaf(origin) =>
        val acc = accVar.getOrElse(
          throw new IllegalStateException(
            "BackendScalaPegFastparse: OpLeaf outside an operator context"
          )
        )
        originExpr(origin, s"($acc +: $kidsVar)")
      case IRProv.Wrap(origin, innerSpan, inner) =>
        val innerKids = s"innerKids$depth"
        val ownKids = s"ownKids$depth"
        val innerExpr = tagExpr(inner, innerKids, accVar, depth + 1)
        s"{ val ($innerKids, $ownKids) = $kidsVar.splitAt($innerSpan); " +
          s"${originExpr(origin, s"($innerExpr +: $ownKids)")} }"

  // One symbol's own fastparse combinator (a synthetic-char terminal match or a recursive rule
  // call) — every symbol parser has type `P[Cst]`, so a sequence's own combined type is a flat
  // tuple of exactly that many `Cst`s (fastparse auto-flattens `~`-chained tuples).
  private def symParser(sym: IRRewrittenSym): String = sym match
    case IRRewrittenSym.Terminal(label)   => s"term(${strLit(label)})"
    case IRRewrittenSym.NonTerminal(rule) => parseFnName(rule)

  // A sequence of `n` symbols chained with `~`, its captured kids pattern-matched into `k0..k(n-1)`
  // — fastparse gives a bare value (not a 1-tuple) for a single combinator and no tuple at all for
  // zero, so those arities are special-cased; `n >= 2` is an ordinary flat tuple.
  private def seqParser(syms: Vector[IRRewrittenSym]): String =
    syms.map(symParser).mkString(" ~ ")

  private def kidsPattern(n: Int): String = n match
    case 0 => "_"
    case 1 => "k0"
    case _ => s"(${(0 until n).map(i => s"k$i").mkString(", ")})"

  private def kidsVec(n: Int): String = s"Vector(${(0 until n).map(i => s"k$i").mkString(", ")})"

  // One `Plain`/base alt's own parser: match its sequence, tag the result — a self-contained
  // `P[Cst]` needing no accumulator.
  private def altParser(alt: IRRewrittenAlt): String =
    val n = alt.syms.length
    val tagged = tagExpr(alt.prov, kidsVec(n), accVar = None, depth = 0)
    if n == 0 then s"Pass(($tagged))"
    else s"(${seqParser(alt.syms)}).map { case ${kidsPattern(n)} => $tagged }"

  // One `Folded` operator alt's own RAW parser: match its sequence, but yield only its own kids
  // (as a `Vector[Cst]`) — tagging is deferred to `ruleFn`'s post-`.rep` fold, since `IRProv`
  // resolution for an operator needs the fold's running accumulator, not known until fold time.
  private def opRawParser(alt: IRRewrittenAlt): String =
    val n = alt.syms.length
    if n == 0 then "Pass(Vector.empty[Cst])"
    else s"(${seqParser(alt.syms)}).map { case ${kidsPattern(n)} => ${kidsVec(n)} }"

  private def orChain(exprs: Vector[String]): String =
    exprs.reduceLeft((acc, e) => s"($acc | $e)")

  private def ruleFn(r: IRRewrittenRule): String =
    val fnName = parseFnName(r.name)
    r.body match
      case IRRuleBody.Plain(alts) =>
        s"def $fnName[$$: P]: P[Cst] = P(${orChain(alts.map(altParser))})"
      case IRRuleBody.Folded(bases, operators) =>
        val baseExpr = orChain(bases.map(altParser))
        val opTags = operators.zipWithIndex.map { case (op, i) =>
          s"          case $i => ${tagExpr(op.prov, "kids", Some("acc"), depth = 0)}"
        }
        s"""def $fnName[$$: P]: P[Cst] = P(
  ($baseExpr) ~ (${orChain(operators.zipWithIndex.map { case (op, i) =>
            s"(${opRawParser(op)}).map(kids => ($i, kids))"
          })}).rep
).map { case (base, ops) =>
  def tagOp(opIdx: Int, acc: Cst, kids: Vector[Cst]): Cst = opIdx match {
${opTags.mkString("\n")}
    case other => throw new IllegalStateException(s"unknown operator index $$other")
  }
  ops.foldLeft(base) { case (acc, (opIdx, kids)) => tagOp(opIdx, acc, kids) }
}"""

  private def preamble: String =
    Vector(
      "import fastparse._, NoWhitespace._",
      "",
      "final case class Token(terminal: String, text: String)",
      "",
      "enum Cst derives CanEqual:",
      "  case Branch(rule: Int, kids: Vector[Cst])",
      "  case Token(terminal: String, text: String)"
    ).mkString("\n")

  // Every generated function starts at column 0; `indented` (shared shift-by-one-level logic,
  // mirroring `BackendScalaPeg`'s own) nests the whole module inside `object <Name>:`.
  private def indented(body: String): String =
    body.linesIterator.map(l => if l.isEmpty then l else s"  $l").mkString("\n")

  /** Emit the `<Name>Fastparse.scala` module, or an error-commented stub if `ir.rewritten` is
    * absent — same conditions/rationale as `BackendScalaPeg.emit`'s own stub.
    */
  def emit(ir: IR): String =
    val objName = safeObjName(ir.grammar.name)
    ir.rewritten match
      case None =>
        banner(ir, "fastparse PEG parser") +
          s"\nobject $objName:\n" +
          "  // ERROR: no rewritten grammar on this IR — build with --strategy ll-star,\n" +
          "  // or this grammar's own shape isn't yet supported (see IR.rewrittenGrammarOf's doc).\n" +
          "  def recognize(toks: Vector[Nothing]): Boolean = throw new RuntimeException(\"unavailable\")\n"
      case Some(rg) =>
        val fns = rg.rules.map(ruleFn)
        val startFn = parseFnName(rg.start)
        // A synthetic per-terminal Char alphabet (Private Use Area, ``+, escaped rather
        // than embedded raw in the generated SOURCE TEXT) built fresh from `tokens` —
        // `fastparse`'s own `CharPred`/`Index` combinators then drive matching over `input` (a
        // same-length synthetic String), never over `tokens` directly. See the module header for
        // why: `fastparse.ParserInput` cannot consume a token stream itself. `￿` (a reserved
        // noncharacter, never assigned by `termChar`) is the "never matches" sentinel for a
        // terminal absent from this call's own token vector.
        val driverMembers = Vector(
          """private val termChar: Map[String, Char] =
  tokens.map(_.terminal).distinct.zipWithIndex.map { case (t, i) => t -> (0xE000 + i).toChar }.toMap
private val input: String = tokens.map(t => termChar.getOrElse(t.terminal, '\uFFFF')).mkString

def term[$: P](label: String): P[Cst] =
  val ch = termChar.getOrElse(label, '\uFFFF')
  // fastparse elides a Unit-typed result from a `~` chain, so `Index ~ CharPred(...)` is
  // `P[Int]`, not `P[(Int, Unit)]` — verified by actually compiling this (a tuple pattern here
  // fails with a confusing "Found: Any, Required: Int" instead of a clear arity mismatch).
  P(Index ~ CharPred(_ == ch)).map { idx =>
    Cst.Token(tokens(idx).terminal, tokens(idx).text)
  }""",
          fns.mkString("\n\n"),
          s"""def parseAll: Option[Cst] =
  fastparse.parse(input, $startFn(using _)) match {
    case Parsed.Success(cst, idx) if idx == input.length => Some(cst)
    case _ => None
  }
def recognizeAll: Boolean = parseAll.isDefined"""
        ).mkString("\n\n")
        val driverClass =
          s"private class Driver(tokens: Vector[Token]):\n${indented(driverMembers)}"
        val body = Vector(
          preamble,
          "",
          driverClass,
          "",
          "def parse(tokens: Vector[Token]): Option[Cst] = Driver(tokens).parseAll",
          "def recognize(tokens: Vector[Token]): Boolean = Driver(tokens).recognizeAll"
        ).mkString("\n")
        Vector(
          banner(ir, "fastparse PEG parser (strategy ll-star)"),
          "",
          s"object $objName:",
          indented(body)
        ).mkString("\n")
