package gramark

// A `Cst`-capable, dependency-free codegen backend: `gramark-ir` in, a self-contained Scala PEG
// (ordered-choice recursive-descent) parser out — `IR.rewritten`'s first *executable* consumer.
//
// Unlike `atn-ts` (deliberately recognizer-only, `docs/all-star-port-plan.md` Phase 5), this
// reaches real CST parity with `Ll.parse`: `IR.rewritten` already carries every alt's resolved
// `IRProv` (see `IR.scala`), so codegen only has to translate that static tree into Scala
// expressions, never interpret it at runtime.
//
// Each `IRRewrittenRule` becomes one `parse<Name>` function, dispatching on its `IRRuleBody`:
//   - `Plain(alts)`: ordered choice, tried in the IR's own order (already `Unwrap`-last — see
//     `IR.rewrittenGrammarOf`'s doc for why re-sorting here would reintroduce the PEG "hiding
//     problem" `IRRuleBody.Folded` and the reordering both exist to avoid).
//   - `Folded(bases, operators)`: match one of `bases` once, then a real greedy loop over
//     `operators`, left-folding each match onto the accumulator — the direct Scala translation of
//     `IRRewrittenSuite`'s own reference-walker `loop` function, which is this backend's design
//     proof; the parity gate (`ScalaPegParityMain`/`check-scala-peg-parity.mjs`) proves the
//     translation is faithful by actually compiling and running the emitted code.
//
// `ident`/`strLit`/`originExpr`/`tagExpr`/`indented` are `private[gramark]` (not `private`) so
// `BackendScalaPegCombinators` (Phase 4's opt-in, `scala-parser-combinators`-based backend, which
// reads the same `IRRewritten*` shapes and needs the identical `IRProv`-to-Cst-tagging-expression
// translation, just wired into a different sequencing library) can reuse them verbatim rather
// than duplicating a second, driftable copy.
object BackendScalaPeg:
  val backend: Backend = Backend(
    name = "scala-peg",
    capabilities = Vector(Capability.Cst),
    strategies = Vector("ll-star"),
    emit = ir => Vector(Output(s"${ir.grammar.name}.scala", emit(ir)))
  )

  private def banner(ir: IR, what: String): String =
    s"// GENERATED by Gramark from the `${ir.grammar.name}` grammar — $what.\n" +
      "// Do not edit; regenerate with `gramark emit --backend scala-peg --strategy ll-star`."

  private[gramark] def strLit(s: String): String =
    "\"" + s.flatMap {
      case '"'  => "\\\""
      case '\\' => "\\\\"
      case '\n' => "\\n"
      case '\t' => "\\t"
      case '\r' => "\\r"
      case c    => c.toString
    } + "\""

  // A grammar rule name is a `.grmk.md` identifier already (letters/digits/underscore) — this is
  // a defensive normalization, not something the real corpus ever exercises, so an arbitrary
  // (deterministic) substitution for anything else is fine.
  private[gramark] def ident(name: String): String =
    val safe = name.map(c => if c.isLetterOrDigit || c == '_' then c else '_')
    if safe.headOption.exists(_.isDigit) then s"_$safe" else safe

  private[gramark] def parseFnName(rule: String): String = s"parse_${ident(rule)}"

  private[gramark] val scalaKeywords: Set[String] = Set(
    "abstract",
    "case",
    "catch",
    "class",
    "def",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "final",
    "finally",
    "for",
    "given",
    "if",
    "implicit",
    "import",
    "lazy",
    "match",
    "new",
    "null",
    "object",
    "override",
    "package",
    "private",
    "protected",
    "return",
    "sealed",
    "super",
    "then",
    "this",
    "throw",
    "trait",
    "true",
    "try",
    "type",
    "val",
    "var",
    "while",
    "with",
    "yield"
  )

  // A grammar's own declared name becomes a top-level `object` declaration — unlike a rule name
  // (always prefixed `parse_` via `parseFnName`, so a keyword collision is impossible there), this
  // has no such prefix protection. `ident` only strips non-identifier characters, never checks
  // for a Scala reserved word, so a grammar literally named `type`/`object`/`match`/etc. would
  // otherwise emit an uncompilable `object type:`. Backtick-quoting only on an actual collision
  // (not unconditionally) keeps every existing non-keyword grammar name's generated code —
  // and its committed goldens — byte-unchanged.
  private[gramark] def safeObjName(name: String): String =
    val id = ident(name)
    if scalaKeywords.contains(id) then s"`$id`" else id

  private[gramark] def originExpr(origin: IRAltOrigin, kidsExpr: String): String = origin match
    case IRAltOrigin.Unwrap           => s"$kidsExpr.head"
    case IRAltOrigin.Original(prodId) => s"Cst.Branch($prodId, $kidsExpr)"

  // Translates one alt's `IRProv` to a Scala expression computing its tagged `Cst`, given
  // `kidsVar` (a `Vector[Cst]` already bound in scope) and — only meaningful inside a `Folded`
  // rule's own operator alts — `accVar` (the fold's running accumulator). Mirrors
  // `IRRewrittenSuite.resolveProv` exactly, just emitting Scala source instead of interpreting.
  private[gramark] def tagExpr(
      prov: IRProv,
      kidsVar: String,
      accVar: Option[String],
      depth: Int
  ): String =
    prov match
      case IRProv.Leaf(origin) => originExpr(origin, kidsVar)
      case IRProv.OpLeaf(origin) =>
        val acc = accVar.getOrElse(
          throw new IllegalStateException("BackendScalaPeg: OpLeaf outside an operator context")
        )
        originExpr(origin, s"($acc +: $kidsVar)")
      case IRProv.Wrap(origin, innerSpan, inner) =>
        val innerKids = s"innerKids$depth"
        val ownKids = s"ownKids$depth"
        val innerExpr = tagExpr(inner, innerKids, accVar, depth + 1)
        s"{ val ($innerKids, $ownKids) = $kidsVar.splitAt($innerSpan); " +
          s"${originExpr(origin, s"($innerExpr +: $ownKids)")} }"

  // One alt's full match-and-tag body: a brace-delimited for-comprehension over its own symbols
  // (each a terminal match or a recursive rule call), starting from `startPos`, yielding
  // `(taggedCst, posAfter)`. Every block below uses explicit `{ }` rather than relying on Scala
  // 3's significant-indentation rule — the codegen only tracks string content, not column
  // position, so off-side-rule indentation is not safely derivable here.
  private def altBody(alt: IRRewrittenAlt, startPos: String, accVar: Option[String]): String =
    val n = alt.syms.length
    val posName: Int => String = i => if i == 0 then startPos else s"p$i"
    val steps = alt.syms.zipWithIndex.map { case (sym, i) =>
      val kid = s"k$i"
      val posIn = posName(i)
      val posOut = posName(i + 1)
      sym match
        case IRRewrittenSym.Terminal(label) =>
          s"($kid, $posOut) <- matchTerminal(toks, $posIn, ${strLit(label)})"
        case IRRewrittenSym.NonTerminal(rule) =>
          s"($kid, $posOut) <- ${parseFnName(rule)}(toks, $posIn)"
    }
    val kidsVec = s"Vector(${(0 until n).map(i => s"k$i").mkString(", ")})"
    val finalPos = posName(n)
    val tagged = tagExpr(alt.prov, kidsVec, accVar, depth = 0)
    if n == 0 then s"Some(($tagged, $finalPos))"
    else s"for { ${steps.mkString("; ")} } yield ($tagged, $finalPos)"

  // No leading parenthesis on the result: this string is always embedded as the first token of
  // its own line, immediately after a previous statement — a leading `(` there is a real bug, not
  // a style nit. Scala's newline-vs-continuation rule attaches a line starting with `(` to the
  // PRECEDING line's trailing token as a function application (`None` \n `(x)` parses as
  // `None(x)`, only failing at type-check time with a confusing "does not take parameters"
  // error) — verified by compiling the generated output directly, not just reasoned about.
  private def orElseChain(exprs: Vector[String]): String =
    exprs.reduceLeft((acc, e) => s"$acc.orElse($e)")

  // Every generated function starts at column 0 — the caller (`emit`, via `indented`) shifts the
  // whole module uniformly by one level when nesting it inside `object $name:`, so this only ever
  // has to get ITS OWN relative nesting right, not guess the column it will end up printed at.
  private def ruleFn(r: IRRewrittenRule): String =
    val fnName = parseFnName(r.name)
    r.body match
      case IRRuleBody.Plain(alts) =>
        val altDefs = alts.zipWithIndex.map { case (a, i) =>
          s"  def alt$i: Option[(Cst, Int)] = ${altBody(a, "pos", None)}"
        }
        val chain = orElseChain(alts.indices.map(i => s"alt$i").toVector)
        s"""def $fnName(toks: Vector[Token], pos: Int): Option[(Cst, Int)] = {
${altDefs.mkString("\n")}
  $chain
}"""
      case IRRuleBody.Folded(bases, operators) =>
        val baseDefs = bases.zipWithIndex.map { case (a, i) =>
          s"  def base$i: Option[(Cst, Int)] = ${altBody(a, "pos", None)}"
        }
        val baseChain = orElseChain(bases.indices.map(i => s"base$i").toVector)
        val opDefs = operators.zipWithIndex.map { case (a, i) =>
          s"    def op$i(p: Int): Option[(Cst, Int)] = ${altBody(a, "p", Some("acc"))}"
        }
        val opChain = orElseChain(operators.indices.map(i => s"op$i(p)").toVector)
        s"""def $fnName(toks: Vector[Token], pos: Int): Option[(Cst, Int)] = {
${baseDefs.mkString("\n")}
  $baseChain.map { case (baseCst, basePos) =>
    @scala.annotation.tailrec
    def loop(acc: Cst, p: Int): (Cst, Int) = {
${opDefs.mkString("\n")}
      $opChain match {
        case None             => (acc, p)
        case Some((next, p2)) => loop(next, p2)
      }
    }
    loop(baseCst, basePos)
  }
}"""

  private val preamble: String =
    Vector(
      "final case class Token(terminal: String, text: String)",
      "",
      "enum Cst derives CanEqual:",
      "  case Branch(rule: Int, kids: Vector[Cst])",
      "  case Token(terminal: String, text: String)",
      "",
      "def matchTerminal(toks: Vector[Token], pos: Int, label: String): Option[(Cst, Int)] =",
      "  toks.lift(pos).filter(_.terminal == label).map(t => (Cst.Token(t.terminal, t.text), pos + 1))"
    ).mkString("\n")

  // Every line of `body` shifted one indent level deeper, for nesting inside `object $name:`
  // below — the ONE place this backend relies on Scala's off-side rule (a `object name:` block's
  // own top-level members just need consistent indentation, not any exact column), since wrapping
  // the whole module keeps each generated grammar in its own namespace: a `Token`/`Cst`/`parse`
  // defined by one grammar's generated file can never collide with another's on the same
  // classpath (`codegen-scratch`'s parity driver may compile more than one grammar's output at
  // once — see Phase 3 of the PEG-engine plan).
  private[gramark] def indented(body: String): String =
    body.linesIterator.map(l => if l.isEmpty then l else s"  $l").mkString("\n")

  /** Emit the `<Name>.scala` module (a single `object <Name>:` — see `indented`'s doc for why), or
    * an error-commented stub if `ir.rewritten` is absent (shouldn't happen via `gramark emit`,
    * which gates on `--strategy ll-star` before calling any backend — defensive for a caller that
    * constructs/invokes this backend directly, or whose grammar `IR.rewrittenGrammarOf` declined,
    * e.g. a genuinely mutually left-recursive one).
    */
  def emit(ir: IR): String =
    val objName = safeObjName(ir.grammar.name)
    ir.rewritten match
      case None =>
        banner(ir, "PEG parser") +
          s"\nobject $objName:\n" +
          "  // ERROR: no rewritten grammar on this IR — build with --strategy ll-star,\n" +
          "  // or this grammar's own shape isn't yet supported (see IR.rewrittenGrammarOf's doc).\n" +
          "  def recognize(toks: Vector[Nothing]): Boolean = throw new RuntimeException(\"unavailable\")\n"
      case Some(rg) =>
        val fns = rg.rules.map(ruleFn)
        val startFn = parseFnName(rg.start)
        val body = Vector(
          preamble,
          "",
          fns.mkString("\n\n"),
          s"""def parse(toks: Vector[Token]): Option[Cst] =
  $startFn(toks, 0).collect { case (cst, pos) if pos == toks.length => cst }
""",
          """def recognize(toks: Vector[Token]): Boolean = parse(toks).isDefined"""
        ).mkString("\n")
        Vector(
          banner(ir, "PEG parser (strategy ll-star)"),
          "",
          s"object $objName:",
          indented(body)
        ).mkString("\n")
