package gramark

// A `Cst`-capable, `scala-parser-combinators`-based codegen backend — Phase 4 of the PEG-engine
// plan (docs/all-star-port-plan.md), reading the same `IR.rewritten` section `BackendScalaPeg`
// (the dependency-free backend, Phase 2) does.
//
// Originally planned around `fastparse` for "production-grade performance", but fastparse's
// `ParserInput` is fundamentally `Char`/`Byte`-oriented (confirmed: its only supported inputs are
// `String`, `Array[Byte]`, `java.io.InputStream`, or another `geny.Readable` — no generic
// token-stream support), while this port's whole pipeline works over a pre-lexed `Vector[Token]`.
// `scala.util.parsing.combinator.Parsers` is generic over `type Elem`, so it parses a token
// stream directly via a custom `Reader[Token]` — no character-encoding workaround needed — at the
// cost of being a separately-versioned, less actively maintained module than fastparse (a real
// tradeoff, not a free substitution; recorded in the PEG-engine plan's own ADR).
//
// The two correctness properties `BackendScalaPeg` established are properties of ANY ordered-
// choice combinator library, not something specific to hand-rolled backtracking, so both carry
// over unchanged: `scala-parser-combinators`' own `|` commits to the first alternative that
// locally succeeds — it does NOT retry a different alternative merely because something AFTER the
// `|` later fails (the same PEG "hiding problem" `BackendScalaPeg`'s own doc explains) — so
// `IRRuleBody.Plain` still needs its `Unwrap`-last ordering, and `IRRuleBody.Folded` still needs
// its explicit repetition (`rep`) shape rather than raw ordered "no-tail | with-tail" alts.
//
// Reuses `BackendScalaPeg`'s `ident`/`strLit`/`originExpr`/`tagExpr`/`indented` (widened to
// `private[gramark]` there) for the identical `IRProv`-to-Cst-tagging-expression translation —
// only the sequencing/matching syntax differs between the two backends.
object BackendScalaPegCombinators:
  val backend: Backend = Backend(
    name = "scala-peg-combinators",
    capabilities = Vector(Capability.Cst),
    strategies = Vector("ll-star"),
    emit = ir => Vector(Output(s"${ir.grammar.name}.scala", emit(ir)))
  )

  private def banner(ir: IR, what: String): String =
    s"// GENERATED by Gramark from the `${ir.grammar.name}` grammar — $what.\n" +
      "// Do not edit; regenerate with `gramark emit --backend scala-peg-combinators --strategy ll-star`."

  // One alt's parser expression: sequences its own symbols via `~`, then `^^` to build+tag the
  // resulting `Cst`. `forOp = false` (an ordinary `Plain`/`Folded.bases` alt) produces a
  // `Parser[Cst]`; `forOp = true` (a `Folded.operators` alt) produces a `Parser[Cst => Cst]` — a
  // function from the fold's running accumulator to the next one, since `rep`'s own repetitions
  // have no way to thread a changing accumulator INTO each step directly (unlike `BackendScalaPeg`'s
  // hand-rolled tail-recursive loop, which passes `acc` as a real parameter) — the fold happens
  // afterward, at the `rep` call site in `ruleFn`, by applying each step function in turn.
  private def altParser(alt: IRRewrittenAlt, forOp: Boolean): String =
    val n = alt.syms.length
    val binders = (0 until n).map(i => s"k$i")
    val kidsVec = s"Vector(${binders.mkString(", ")})"
    val accVar = if forOp then Some("__acc") else None
    val tagged = BackendScalaPeg.tagExpr(alt.prov, kidsVec, accVar, depth = 0)
    val result = if forOp then s"(__acc: Cst) => $tagged" else tagged
    val terms = alt.syms.map {
      case IRRewrittenSym.Terminal(label)   => s"term(${BackendScalaPeg.strLit(label)})"
      case IRRewrittenSym.NonTerminal(rule) => BackendScalaPeg.parseFnName(rule)
    }
    n match
      case 0 => s"success($result)"
      case 1 => s"(${terms.head} ^^ { ${binders.head} => $result })"
      case _ =>
        val seq = terms.mkString(" ~ ")
        val pattern = binders.mkString(" ~ ")
        s"((${seq}) ^^ { case $pattern => $result })"

  private def orChain(exprs: Vector[String]): String = exprs.mkString(" | ")

  private def ruleFn(r: IRRewrittenRule): String =
    val fnName = BackendScalaPeg.parseFnName(r.name)
    r.body match
      case IRRuleBody.Plain(alts) =>
        val altExprs = alts.map(a => altParser(a, forOp = false))
        s"def $fnName: Parser[Cst] = ${orChain(altExprs)}"
      case IRRuleBody.Folded(bases, operators) =>
        val baseExprs = bases.map(a => altParser(a, forOp = false))
        val opExprs = operators.map(a => altParser(a, forOp = true))
        s"""def $fnName: Parser[Cst] = {
  val __base: Parser[Cst] = ${orChain(baseExprs)}
  val __step: Parser[Cst => Cst] = ${orChain(opExprs)}
  (__base ~ rep(__step)) ^^ { case base ~ steps => steps.foldLeft(base) { (acc, step) => step(acc) } }
}"""

  private val preamble: String =
    Vector(
      "final case class Token(terminal: String, text: String)",
      "",
      "enum Cst derives CanEqual:",
      "  case Branch(rule: Int, kids: Vector[Cst])",
      "  case Token(terminal: String, text: String)",
      "",
      // An index into the SAME underlying `Vector`, not a `.tail`-sliced copy per step — `Vector`
      // indexing is O(1), so this avoids any repeated-slicing cost across a long token stream.
      "final case class TokenReader(tokens: Vector[Token], index: Int = 0) extends Reader[Token]:",
      "  def first: Token = tokens(index)",
      "  def atEnd: Boolean = index >= tokens.length",
      "  def pos: Position = NoPosition",
      "  def rest: Reader[Token] = TokenReader(tokens, index + 1)",
      "",
      "def term(label: String): Parser[Cst] =",
      "  accept(label, { case t if t.terminal == label => Cst.Token(t.terminal, t.text) })"
    ).mkString("\n")

  /** Emit the `<Name>.scala` module (a single `object <Name> extends Parsers:`, `type Elem = Token`
    * — see `BackendScalaPeg.indented`'s doc for why the whole module is one object), or an
    * error-commented stub if `ir.rewritten` is absent.
    */
  def emit(ir: IR): String =
    val objName = BackendScalaPeg.safeObjName(ir.grammar.name)
    ir.rewritten match
      case None =>
        banner(ir, "PEG parser (scala-parser-combinators)") +
          s"\nobject $objName:\n" +
          "  // ERROR: no rewritten grammar on this IR — build with --strategy ll-star,\n" +
          "  // or this grammar's own shape isn't yet supported (see IR.rewrittenGrammarOf's doc).\n" +
          "  def recognize(toks: Vector[Nothing]): Boolean = throw new RuntimeException(\"unavailable\")\n"
      case Some(rg) =>
        val fns = rg.rules.map(ruleFn)
        val startFn = BackendScalaPeg.parseFnName(rg.start)
        val body = Vector(
          preamble,
          "",
          fns.mkString("\n\n"),
          s"""def parse(toks: Vector[Token]): Option[Cst] =
  $startFn(TokenReader(toks)) match {
    case Success(cst, rest) if rest.atEnd => Some(cst)
    case _                                => None
  }""",
          """def recognize(toks: Vector[Token]): Boolean = parse(toks).isDefined"""
        ).mkString("\n")
        Vector(
          banner(ir, "PEG parser (scala-parser-combinators, strategy ll-star)"),
          "",
          // Imports must precede the `object ... extends Parsers:` line, not live inside its own
          // body — the `extends` clause resolves `Parsers` before any import nested in the body
          // would take effect (verified by actually compiling this: nesting the imports inside
          // produced a "Not found: Parsers" error on the object header itself).
          "import scala.util.parsing.combinator.Parsers",
          "import scala.util.parsing.input.{NoPosition, Position, Reader}",
          "",
          s"object $objName extends Parsers:",
          "  type Elem = Token",
          BackendScalaPeg.indented(body)
        ).mkString("\n")
